### ISSUE TITLE
support of Xiaomi Temperature sensor

### ISSUE THREAD

**Issue by zeno-at** [madchicken/homebridge-zigbee-nt#1]
unfortunately I cannot pair Xiaomi temperature sensor! in your supported device list Xiaomi is not listed, is this my problem ?

**Comment by madchicken** [comment]
No, Xiaomi devices are not currently supported, but it should be easy to add them since I see they are supported by zigbee-herdsman

**Comment by zeno-at** [comment]
may I hope for a fast solution? thx

**Comment by madchicken** [comment]
Definitely yes. I am solving some basic problem on this plugin. After that I'll start adding more devices. At the moment I started from devices I own, to be able to test them

**Comment by manuchis** [comment]
I've been trying to pair an Aqara sensor with RC2, supposedly the same spects than Xiaomi, and its not working:

My db:
'{"id":2,"type":"EndDevice","ieeeAddr":"0x00158d00047b5957","nwkAddr":56475,"manufId":4151,"manufName":"LUMI","powerSource":"Battery","modelId":"lumi.weather","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":770,"inClusterList":[0,3,65535,1026,1027,1029],"outClusterList":[0,4,65535],"clusters":{"genBasic":{"attributes":{"65281":{"1":2995,"4":424,"5":5,"6":[0,1],"10":44475,"100":2984,"101":7225,"102":101438},"manufacturerName":"LUMI","powerSource":3,"zclVersion":1,"stackVersion":2,"modelId":"lumi.weather","appVersion":5,"dateCode":"20191205","swBuildId":"3000-0001"}},"msTemperatureMeasurement":{"attributes":{"measuredValue":2916}},"msRelativeHumidity":{"attributes":{"measuredValue":7635}},"msPressureMeasurement":{"attributes":{"16":10145,"20":-1,"measuredValue":1014}}},"binds":[]}},"appVersion":5,"stackVersion":2,"dateCode":"20191205","swBuildId":"3000-0001","zclVersion":1,"interviewCompleted":true,"meta":{},"lastSeen":1594221551831}'

In zigbee-herdsman converters: 
 {
        zigbeeModel: ['lumi.weather'],
        model: 'WSDCGQ11LM',
        vendor: 'Xiaomi',
        description: 'Aqara temperature, humidity and pressure sensor',
        supports: 'temperature, humidity and pressure',
        fromZigbee: [
            fz.xiaomi_battery_3v, fz.xiaomi_temperature, fz.humidity, fz.WSDCGQ11LM_pressure,
            fz.WSDCGQ01LM_WSDCGQ11LM_interval,
        ],
        toZigbee: [],
    },

**Comment by madchicken** [comment]
Is the plugin recognising the device? Or it simply prints `Unrecognized device: ...`?

**Comment by bcharbonnier** [comment]
I also did not manage to pair an Aqara temp/humidity/pressure.

The pairing seems to go normal, the device is found, it shows “Found ZigBee device: “ (with the configuration detected and then next log is “unrecognized ZigBee device ...”

Nonetheless, the address seems good, the manufacturer and model are ok, and then I can also see in the logs messages coming from it, but discarded as “No device found...”

It seems Tahar everything should be working but for whatever reason when the actual HomeKit device should be created it’s not...

I can provide more logs if needed! Thanks for the awesome work done here! 👍

**Comment by madchicken** [comment]
I think the problem is the manufacturer name that is different: I used Xiaomi when from the json posted above is LUMI. We can fix it easily by changing the registration string

**Comment by manuchis** [comment]
Yes, maybe. I will give a try later.

Manuel Portela, PhD
Cel Es. +34 600 851 104
Follow me: @Portela_Man
manuchis.net

**Comment by bcharbonnier** [comment]
Thanks @madchicken! Works like a charm now!
