### ISSUE TITLE
Error code

### ISSUE THREAD

**Issue by daxterone** [madchicken/homebridge-zigbee-nt#105]
I see in the log the following error which appears several times an hour.

`[1/30/2021, 2:56:40 PM] [Sonos] error: unhandled rejection: Error: Write 0x04cf8cdf3c7dd91f/1 aqaraOpple({"mode":1}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":4447,"transactionSequenceNumber":null}) failed (Data request failed with error: 'MAC transaction expired' (240))
    at ZStackAdapter.<anonymous> (/usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:367:23)
    at Generator.next (<anonymous>)
[homebridge.log](https://github.com/ebaauw/homebridge-zp/files/5898121/homebridge.log)
    at fulfilled (/usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:24:58) `

**Comment by daxterone** [comment]
log is attached
[homebridge.log](https://github.com/madchicken/homebridge-zigbee-nt/files/5903526/homebridge.log)

**Comment by tr1ng0** [comment]
@daxterone is the device working correctly? Mine are working well so far

**Comment by madchicken** [comment]
I see the configuration procedure for this type of device is setting the mode to 1:

https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices.js#L1061
