### ISSUE TITLE
Request to add Zigbee Wall Switch recognized as TUYATEC TS0011

### ISSUE THREAD

**Issue by TrapMusicJunkie** [madchicken/homebridge-zigbee-nt#109]
Hi. I have recently bough a Zigbee Wall Switch which is recognized as TUYATEC TS0011 using homebridge-zigbee-nt plugin. It seems like it is paired correctly but it is not mapped into accessories in Homebridge. 

I get the following info in the log file:

[31/01/2021, 21:15:41] [ZigBee] No device found from message {
  type: 'attributeReport',
  device: Device {
    ID: 2,
    _type: 'EndDevice',
    _ieeeAddr: '0xec1bbdfffe6b8995',
    _networkAddress: 4937,
    _manufacturerID: 0,
    _endpoints: [ [Endpoint] ],
    _manufacturerName: 'TUYATEC-p9HCE8pZ',
    _powerSource: 'Battery',
    _modelID: 'TS0011',
    _applicationVersion: 70,
    _stackVersion: 0,
    _zclVersion: 2,
    _hardwareVersion: 1,
    _dateCode: '20180608',
    _softwareBuildID: undefined,
    _interviewCompleted: true,
    _interviewing: false,
    meta: {},
    _lastSeen: 1612124141175,
    _linkquality: 118
  },
  endpoint: Endpoint {
    ID: 1,
    profileID: 260,
    deviceID: 256,
    inputClusters: [ 0, 3, 6 ],
    outputClusters: [ 25 ],
    deviceNetworkAddress: 4937,
    deviceIeeeAddress: '0xec1bbdfffe6b8995',
    clusters: { genOnOff: [Object], genBasic: [Object] },
    _binds: [],
    _configuredReportings: [],
    meta: {}
  },
  data: { appVersion: 70 },
  linkquality: 118,
  groupID: 0,
  cluster: 'genBasic',
  meta: {
    zclTransactionSequenceNumber: 100,
    manufacturerCode: null,
    frameControl: {
      frameType: 0,
      manufacturerSpecific: false,
      direction: 1,
      disableDefaultResponse: true,
      reservedBits: 0
    }
  }
}

My setup:
Raspberry Pi3
CC2531 USB dongle
Homebridge
Zigbee Wall Switch

I kindly ask for support in adding this device. 
It would be much appreciated.

Thanks 
<img width="1142" alt="Zrzut ekranu 2021-01-30 o 22 57 26" src="https://user-images.githubusercontent.com/78150989/106396759-48dfa900-640a-11eb-944b-5f9f0dfc77fd.png">
in advance.

**Comment by TrapMusicJunkie** [comment]
OK. I managed to add the device it was as simple as adding additional code:

"devices": [
                {
                    "manufacturer": "TUYATEC-p9HCE8pZ",
                    "models": [
                        "TS0011"
                    ],
                    "services": [
                        {
                            "type": "bulb",
                            "meta": {
                                "brightness": true
                            }
                        }
                    ]
                }
            ]

**Comment by madchicken** [comment]
Thanks, I'll add this config to the internal database
