### ISSUE TITLE
Unable to find ZigBee port

### ISSUE THREAD

**Issue by manuchis** [madchicken/homebridge-zigbee-nt#11]
Suddenly yesterday everything stopped working, I got this error after restarting the RaspberryPi:
```
node:18036) UnhandledPromiseRejectionWarning: Error: Unable to find ZigBee port
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-zigbee-nt/dist/utils/findSerialPort.js:30:15)
    at Generator.next (<anonymous>:null:null)
    at fulfilled (/usr/local/lib/node_modules/homebridge-zigbee-nt/dist/utils/findSerialPort.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

(node:18036) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:18036) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

 I've tried many things but I couldn't find a way.
Any guess?

**Comment by manuchis** [comment]
Update: I fixed it by unplugging the Raspberry, it was the only way. Now I have some devices without response, but going step by step.

**Comment by j4n-co** [comment]
I'm getting this error when running this plugin from a Dockerized Homebridge on my Synology.

Running `dmesg` from inside the Docker container produces the following, so the stick is recognized, I'm just not sure if it's being mounted anywhere. `/dev/ttyACM0` on the docker host does exist though...
 
```
[3310015.608897] usb 1-3: new full-speed USB device number 9 using xhci_hcd
[3310015.754013] cdc_acm 1-3:1.0: ttyACM0: USB ACM device
[3310016.869412] usbcore: deregistering interface driver cdc_acm
[3310019.450188] PPP generic driver version 2.4.2
[3310019.461837] cdc_acm 1-3:1.0: ttyACM0: USB ACM device
[3310019.468641] usbcore: registered new interface driver cdc_acm
[3310019.475386] cdc_acm: USB Abstract Control Model driver for USB modems and ISDN adapters
```

**Comment by oltitov** [comment]
> I'm getting this error when running this plugin from a Dockerized Homebridge on my Synology.
> 
> Running `dmesg` from inside the Docker container produces the following, so the stick is recognized, I'm just not sure if it's being mounted anywhere. `/dev/ttyACM0` on the docker host does exist though...
> 
> ```
> [3310015.608897] usb 1-3: new full-speed USB device number 9 using xhci_hcd
> [3310015.754013] cdc_acm 1-3:1.0: ttyACM0: USB ACM device
> [3310016.869412] usbcore: deregistering interface driver cdc_acm
> [3310019.450188] PPP generic driver version 2.4.2
> [3310019.461837] cdc_acm 1-3:1.0: ttyACM0: USB ACM device
> [3310019.468641] usbcore: registered new interface driver cdc_acm
> [3310019.475386] cdc_acm: USB Abstract Control Model driver for USB modems and ISDN adapters
> ```

Hello Friend! 
I get this error on Synology. 
Please tell me if you managed to solve this problem?

**Comment by jandre3000** [comment]
@oltitov If I remember correctly, in my case this was a permission issue, where Docker did not have permission to read or access `/dev/ttyACM0`. 

What worked for me was to first unplug the stick, load the kernel modules (I think this is necessary for DSM 7.0 now), 
```
/sbin/modprobe usbserial
/sbin/modprobe ftdi_sio
/sbin/modprobe cdc-acm
```
Then check if ` /dev/ttyACM0` exists. If it does, change the permissions `chmod 777 /dev/ttyACM0` and then start the docker container.
