### ISSUE TITLE
Blitzwolf Smart Socket BW-SHP13 Support

### ISSUE THREAD

**Issue by prugala** [madchicken/homebridge-zigbee-nt#113]
Hello
I've tried to add Blitzwolf Smart Socket BW-SHP13 and socket was found but its detected as undefined device.
![device](https://i.imgur.com/QS5Br6r.png)

When I inspect response with device info I see that there is information about status: on/off
![status](https://i.imgur.com/4wGzURQ.png)

There is option to add switch accessory to change it or I have to add support for this device in plugin?

**Comment by tr1ng0** [comment]
Hey @prugala, did you try adding it via configuration?
https://github.com/madchicken/homebridge-zigbee-nt/wiki/Add-new-devices-in-configuration

**Comment by prugala** [comment]
Hi @tr1ng0 thanks for link to documentation. I've added custom device but I don't know that is wrong, for my device should be created accesory? I still have only: "Zigbee Permit Join" and "Zigbee Touchlink".

My custom device configuration:
```
"devices": [
                {
                    "manufacturer": "_TZ3000_g5xawfcq",
                    "models": [
                        "TS0121"
                    ],
                    "services": [
                        {
                            "type": "contact-sensor"
                        }
                    ]
                }
            ]
```

In log I have:
```
Successfully interviewed device: _TZ3000_g5xawfcq - TS0121
[05/02/2021, 19:29:26] [ZigBee] Found ZigBee device:  Device {
  ID: 2,
  _type: 'Router',
  _ieeeAddr: '0x588e81fffed3a2c1',
  _networkAddress: 2793,
  _manufacturerID: 4098,
  _endpoints: [
    Endpoint {
      ID: 1,
      profileID: 260,
      deviceID: 81,
      inputClusters: [Array],
      outputClusters: [Array],
      deviceNetworkAddress: 2793,
      deviceIeeeAddress: '0x588e81fffed3a2c1',
      clusters: [Object],
      _binds: [],
      _configuredReportings: [],
      meta: {}
    }
  ],
_manufacturerName: '_TZ3000_g5xawfcq',
  _powerSource: 'Mains (single phase)',
  _modelID: 'TS0121',
  _applicationVersion: 65,
  _stackVersion: 0,
  _zclVersion: 3,
  _hardwareVersion: 1,
  _dateCode: '',
  _softwareBuildID: undefined,
  _interviewCompleted: true,
  _interviewing: false,
  meta: {},
  _lastSeen: 1612553364742,
  _linkquality: 86
}
```

In web UI I see my device but still dont have created accessory for my device.
![webui](https://i.imgur.com/SGflB7D.png)

**Comment by prugala** [comment]
One more question, I've added meta:
```
"meta": {
                                "power": true,
                                "current": true,
                                "voltage": true
                            }
```

but don't see in Apple Home and Eve app any information about consumption.
