### ISSUE TITLE
Philips Hue Smart Motion Sensor (Philips SML001) - Unrecognized device

### ISSUE THREAD

**Issue by nikoskontothanasis** [madchicken/homebridge-zigbee-nt#116]
Hello I am using this plugin in a rip 4, with CC2531 USB dongle.
Today I bought a Philips Hue smart motion sensor, because I see that it is supported device.  (https://www.zigbee2mqtt.io/devices/9290012607.html) 
I follow the instructions for pairing the device and seemed to be paired, at least on web ui 9000/devices I can see the device, but I can't find it in the Accessories tab on Homebridge.
Can you help me? 
Thanks in advance. 

Please find attached the log file.

[ZigBee] Accepting joining whitelisted device '0x0017880106f7c3a9'
[ZigBee] Device announce: 0x0017880106f7c3a9 (Philips - SML001)
[ZigBee] Found ZigBee device:  Device {
  ID: 4,
  _type: 'EndDevice',
  _ieeeAddr: '0x0017880106f7c3a9',
  _networkAddress: 48802,
  _manufacturerID: 4107,
  _endpoints: [
    Endpoint {
      ID: 1,
      profileID: 49246,
      deviceID: 2128,
      inputClusters: [Array],
      outputClusters: [Array],
      deviceNetworkAddress: 48802,
      deviceIeeeAddress: '0x0017880106f7c3a9',
      clusters: [Object],
      _binds: [],
      _configuredReportings: [],
      meta: {}
    },
    Endpoint {
      ID: 2,
      profileID: 260,
      deviceID: 263,
      inputClusters: [Array],
      outputClusters: [Array],
      deviceNetworkAddress: 48802,
      deviceIeeeAddress: '0x0017880106f7c3a9',
      clusters: {},
      _binds: [],
      _configuredReportings: [],
      meta: {}
    }
  ],
  _manufacturerName: 'Philips',
  _powerSource: 'Battery',
  _modelID: 'SML001',
  _applicationVersion: 2,
  _stackVersion: 1,
  _zclVersion: 1,
  _hardwareVersion: 1,
  _dateCode: '20160630',
  _softwareBuildID: '6.1.0.18912',
  _interviewCompleted: true,
  _interviewing: false,
  meta: {},
  _lastSeen: 1612625492654
}
 [ZigBee] Unrecognized device: 0x0017880106f7c3a9 Philips SML001

**Comment by madchicken** [comment]
Hi, could you see if the version `2.1.0-unstable.3` works for you? I am testing it before releasing.
You can install it by doing:
```
npm i -g homebridge-zigbee-nt@unstable --unsafe-perm
```
