### ISSUE TITLE
Can't pair devices

### ISSUE THREAD

**Issue by danielavron** [madchicken/homebridge-zigbee-nt#122]
Hello,
I am using a cc2531 flashed according to this: https://www.zigbee2mqtt.io/information/flashing_the_cc2531.html?fbclid=IwAR2OsLS1d2C43VVAfe63iHSuUxz2DQ4wDVqyF44zBVV3TMhkLWFcCNAfa1g. I am trying to pair  this device: https://www.zigbee2mqtt.io/devices/QS-Zigbee-S04-2C-LN.html?fbclid=IwAR1sB7WafsKNdbc0ZYVBOZpxLHah5n53_Iw7uiNkLvBvfiJuVQlDYSxIZ_g.

I'm getting this message in the log:

Found ZigBee device:  Device {
  ID: 2,
  _type: 'Router',
  _ieeeAddr: '0x5c0272fffe16b273',
  _networkAddress: 14020,
  _manufacturerID: 4098,
  _endpoints: [
    Endpoint {
      ID: 1,
      profileID: 260,
      deviceID: 256,
      inputClusters: [Array],
      outputClusters: [Array],
      deviceNetworkAddress: 14020,
      deviceIeeeAddress: '0x5c0272fffe16b273',
      clusters: [Object],
      _binds: [Array],
      _configuredReportings: [],
      meta: {}
    },
    Endpoint {
      ID: 2,
      profileID: 260,
      deviceID: 256,
      inputClusters: [Array],
      outputClusters: [],
      deviceNetworkAddress: 14020,
      deviceIeeeAddress: '0x5c0272fffe16b273',
      clusters: {},
      _binds: [Array],
      _configuredReportings: [],
      meta: {}
    }
  ],
  _manufacturerName: '_TYZB01_zsl6z0pw',
  _powerSource: 'Mains (single phase)',
  _modelID: 'TS0003',
  _applicationVersion: 65,
  _stackVersion: 0,
  _zclVersion: 3,
  _hardwareVersion: 1,
  _dateCode: '',
  _softwareBuildID: undefined,
  _interviewCompleted: true,
  _interviewing: false,
  meta: {},
  _lastSeen: 1612892352958
}
[09/02/2021, 17:39:28] [ZigBee] Reuse accessory from cache with uuid e71a185a-6f14-485b-be66-6c52975997f7 and name 0x5c0272fffe16b273
[09/02/2021, 17:39:28] [ZigBee] Registered device: 0x5c0272fffe16b273 _TYZB01_zsl6z0pw TS0003
[09/02/2021, 17:39:28] [ZigBee] Mounting device 2 gang switch module with neutral wire...
[09/02/2021, 17:39:28] [ZigBee] WebSocket server started @ null
[09/02/2021, 17:39:28] [ZigBee] WEB UI Listening on port 9000
[09/02/2021, 17:39:29] [ZigBee] Device 2 gang switch module with neutral wire is a router, install ping
[09/02/2021, 17:39:29] [ZigBee] Device 2 gang switch module with neutral wire successfully configured on attempt 1!

It doesn't show up on HomeKit. 

This is the config:

{
            "name": "ZigBee",
            "panId": 65534,
            "channel": 11,
            "secondaryChannel": "25",
            "adapter": "zstack",
            "routerPollingInterval": 30,
            "disableRouterPolling": false,
            "disableHttpServer": false,
            "disableLed": true,
            "platform": "ZigbeeHomebridgeNTPlatform",
            "devices": [
                {
                    "manufacturer": "_TYZB01_zsl6z0pw",
                    "models": [
                        "TS0003"
                    ],
                    "services": [
                        {
                            "type": "router"
                        }
                    ]
                }
            ]
        }
        
        would appreciate any help I can get.
        

Thanks!

**Comment by maxgrafik** [comment]
I think there is no service type 'router' (as in your config). Maybe you should try 'bulb' (or 'outlet').

**Comment by danielavron** [comment]
When I put bulb it kind of works. First - it only shows one gang and not two. Second - it doesn’t receive feedback from the switch - so it doesn’t know the light turned off.

**Comment by maxgrafik** [comment]
There already seems to be an accessory for a Lonsonho Double switch, albeit with a different manufacturer and model. I guess for your device this is something @madchicken has to add.

**Comment by danielavron** [comment]
Hopefully soon.
