### ISSUE TITLE
Xiaomi A6121 Smart Lock (lumi.lock.v1) support

### ISSUE THREAD

**Issue by paulzhdanov** [madchicken/homebridge-zigbee-nt#123]
Hello @madchicken , do you have a plans for adding vima lock? It seams the lock has quite simple interface (https://github.com/Koenkk/zigbee2mqtt/issues/3521#issuecomment-691364095) and no servo inside, just solenoid (on/off) and already supported by iobroker firmware for instance (https://github.com/ioBroker/ioBroker.zigbee). I'd be glad to be a alpha-tester, my knowledge is not enough to create new device config, but I'm ready to take an active part and learn

**Comment by madchicken** [comment]
Please, wait for v2.1.0 🙂

**Comment by paulzhdanov** [comment]
Wow, fffffantastic :) don't hesitate to involve me as a tester, I'll be more than glad to take a part

**Comment by madchicken** [comment]
@paulzhdanov can you try to install 2.1.0 unstable? Just use this command:
`npm i homebridge-zigbee-nt@unstable -g --unsafe-perm`

**Comment by paulzhdanov** [comment]
@madchicken I missed the notification, pls excuse for delay. After 2.1.0 install I failed to connect the lock:

```
[27/02/2021, 21:54:53] [ZigBee] Zigbee: allowing new devices to join.
[27/02/2021, 21:54:55] [ZigBee] Starting touchlink factory reset...
[27/02/2021, 21:55:06] [ZigBee] Failed to factory reset device through Touchlink

```
I made 6 attempts with the same result. Any ideas what else could be done?

**Comment by madchicken** [comment]
Are you sure this device supports touchline? I don't see it in the description. It probably needs some specific process for pairing...

**Comment by paulzhdanov** [comment]
Well, at least it pairs with MiGateway in the same way as for instance temperature sensor - long press, beeps, go. It has 2 buttons: one for pairing and another for assigning the physical keys, nothing else. Probably you're right, but what other type of pairing it may have?

**Comment by madchicken** [comment]
Stupid question: did you simply try to turn on the permit join switch in Home App and then do the pairing process?

**Comment by paulzhdanov** [comment]
Yep. Same result - nothing happens. I did try even monkey-way - press randomly 2 buttons, release reset button on lock simultaniously with "allowing new devices" message... Is there any "internal log"? I have "Homebridge Debug Mode -D" on, but may be a specific number "Debug level"?..

**Comment by madchicken** [comment]
No, all debug is outputted when you set the `-D` option. This is very weird. Are you sure the device is not already paired? You can check from the web UI.

**Comment by paulzhdanov** [comment]
After upgrade to 2.1.1 lock successfully connected, but...

```
[02/03/2021, 13:13:59] [ZigBee] Initializing ZigBee device: 0x00158d00028e2d8d - lumi.lock.v1 - LUMI
[02/03/2021, 13:13:59] [ZigBee] Reuse accessory from cache with uuid 4b52c091-78c1-49ab-ae8a-f14830767445 and name 0x00158d00028e2d8d
[02/03/2021, 13:13:59] [ZigBee] Device with key LUMI:lumi.lock.v1 not supported. Please open a Github issue for this at https://github.com/madchicken/homebridge-zigbee-nt/issues Device {
  ID: 4,
  _type: 'Router',
  _ieeeAddr: '0x00158d00028e2d8d',
  _networkAddress: 43733,
  _manufacturerID: 4151,
  _endpoints: [
    Endpoint {
      ID: 1,
      profileID: 260,
      deviceID: 10,
      inputClusters: [Array],
      outputClusters: [Array],
      deviceNetworkAddress: 43733,
      deviceIeeeAddress: '0x00158d00028e2d8d',
      clusters: [Object],
      _binds: [],
      _configuredReportings: [],
      meta: {}
    }
  ],
  _manufacturerName: 'LUMI',
  _powerSource: 'Battery',
  _modelID: 'lumi.lock.v1',
  _applicationVersion: 1,
  _stackVersion: 2,
  _zclVersion: 0,
  _hardwareVersion: 37,
  _dateCode: '04-03-2018',
  _softwareBuildID: undefined,
  _interviewCompleted: true,
  _interviewing: false,
  _skipDefaultResponse: false,
  meta: {},
  _lastSeen: 1614683537983
}
(node:13071) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'friendlyName' of null
    at ZigbeeNTHomebridgePlatform.<anonymous> (/usr/local/lib/node_modules/homebridge-zigbee-nt/src/platform.ts:277:60)
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/homebridge-zigbee-nt/dist/platform.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/homebridge-zigbee-nt/dist/platform.js:23:12)
    at ZigbeeNTHomebridgePlatform.initDevice (/usr/local/lib/node_modules/homebridge-zigbee-nt/dist/platform.js:210:16)
    at /usr/local/lib/node_modules/homebridge-zigbee-nt/src/platform.ts:223:66
    at Array.map (<anonymous>)
    at ZigbeeNTHomebridgePlatform.<anonymous> (/usr/local/lib/node_modules/homebridge-zigbee-nt/src/platform.ts:223:47)
    at Generator.next (<anonymous>)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:13071) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:13071) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by paulzhdanov** [comment]
...I deleted all other devices to make sure there are no conflicts between them

**Comment by madchicken** [comment]
Ok, thanks for reporting I'll fix it asap. I am finally adding tests to the codebase, so I can avoid these problems in the future.

**Comment by madchicken** [comment]
Ok, this lock is just exposing a text property (`inserted`) and there is no control over it. It's not presented as a lock mechanism.
I need to implement a custom class for this

**Comment by madchicken** [comment]
@paulzhdanov so, this device does nothing but reporting its status, correct?

**Comment by paulzhdanov** [comment]
Is there anything I can do to help?

**Comment by paulzhdanov** [comment]
@madchicken Status and lock/unlock action. Lock mechanism is a simple solenoid. Also it have one more function to sign/un-sign (physical) keys, but there is separate button next to reset and it can do the same, no need to repeat a complicated function.

Is there anything I can do to help?

**Comment by paulzhdanov** [comment]
Here's detailed description: https://github.com/Koenkk/zigbee2mqtt/issues/3521#issuecomment-691364095

**Comment by madchicken** [comment]
https://github.com/Koenkk/zigbee2mqtt/issues/3521#issuecomment-626796553

**Comment by paulzhdanov** [comment]
You're right. I checked and yes, it reports the state of inserted key (correct key / not correct key), nothing else.

**Comment by paulzhdanov** [comment]
and here's one more link with debug info: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1977

**Comment by madchicken** [comment]
Sorry, I am gonna close this since the device is not fully supported by herdsman lib. Feel free to open a new one once it will be added
