### ISSUE TITLE
unable to see switch on HomeKit 

### ISSUE THREAD

**Issue by galoiring** [madchicken/homebridge-zigbee-nt#124]
I use this Zigbee switch and I found it on the UI as you can see , but dont see it at HomeKit 

<img width="1280" alt="צילום מסך 2021-02-10 ב-1 08 14" src="https://user-images.githubusercontent.com/74841666/107440647-98c21c80-6b3c-11eb-9dc4-fe7c7b1e075c.png">
<img width="1280" alt="צילום מסך 2021-02-10 ב-1 08 08" src="https://user-images.githubusercontent.com/74841666/107440650-9b247680-6b3c-11eb-9641-1c28a4c7bd75.png">

what may be the problem ?

p.s 
the switch : https://www.aliexpress.com/item/4001133814342.html?spm=a2g0s.9042311.0.0.628a4c4dtVJQ8s

**Comment by madchicken** [comment]
This switch is still not supported by this plugin. Is it supported by the herdsman lib? I don't see it in this list:

https://www.zigbee2mqtt.io/information/supported_devices.html#somgoms

**Comment by galoiring** [comment]
this is the somgoms switch , and it does recognize and connect as you can see in the first picture
