### ISSUE TITLE
TRADAFRI LED1624G9 Support

### ISSUE THREAD

**Issue by grrrum** [madchicken/homebridge-zigbee-nt#136]
Hi, 

Not sure if this is the correct place to post this, I am new to this! I have a Zigbee sniffer which appears to be working correctly and supported etc - I have successfully managed to pair a Philips Hue bulb to it previously when testing and it all worked correctly.

I have just bought three Ikea TRADAFRI bulbs, all which have the serial number LED1624G9, which I do not see in the list of currently supported devices. I have checked the Zigbee2MQTT list which shows these bulbs are possible to be supported. Can anyone assist me in how I would go about adding these bulbs to my setup? I can pair the bulb to my dongle but I can't use it as an accessory.

EDIT: So after continuing to fiddle for a while, Ive managed to get all of my bulbs linked up and they turn on/off and somewhat change colour via HomeKit, however the 6 preset colour options are generally wildly out - say I click the orange light button, the bulb will go purple, or white, or maybe even orange. There doesn't seem to be any rhyme nor reason as to which colour is turned on. Is this an issue anyone can assist with?

**Comment by madchicken** [comment]
Yes, I am aware of the problem with preset colors. I still didn't have time to undestand what is going on with them. I want to add adaptive light support (since it is now supported in homebridge 1.3). I'll try to fix this issue along the other changes
