### ISSUE TITLE
Plugin installation for Node v>9 

### ISSUE THREAD

**Issue by gitmarcramos** [madchicken/homebridge-zigbee-nt#155]
Hello,

It seems that this plugin can only run on a Node version below or equal to v9. 
Is there any way to run it with a greater Node version?

Below the error message I get when I try to install the plugin. 

```
required: { node: '>=0.12.0 <9.0.0' },
npm WARN EBADENGINE   current: { node: 'v14.16.0', npm: '7.6.3' }
```

Thanks

**Comment by funnymataleao** [comment]
Same problem here :(

**Comment by funnymataleao** [comment]
npm WARN notsup Unsupported engine for http2@3.3.7: wanted: {"node":">=0.12.0 <9.0.0"} (current: {"node":"14.17.0","npm":"6.14.13"})
npm WARN notsup Not compatible with your version of node/npm: http2@3.3.7
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman-converters/node_modules/zigbee-herdsman/node_modules/fsevents):
