### ISSUE TITLE
zigbee-herdsman recent update breaks the homebridge-zigbee-nt

### ISSUE THREAD

**Issue by wojciechczerniak** [madchicken/homebridge-zigbee-nt#167]
https://github.com/Koenkk/zigbee-herdsman v0.13.96 and above breaks this plugin. https://github.com/Koenkk/zigbee-herdsman/issues/374

```
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'disableLED' of null
    at Controller.<anonymous> (/usr/local/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/src/controller/controller.ts:244:77)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/dist/controller/controller.js:24:58)
```
Introduced in https://github.com/Koenkk/zigbee-herdsman/commit/8d50ba0cd78369b7f93911f00d6a47f7972667df

https://github.com/Koenkk/zigbee-herdsman/blob/8d50ba0cd78369b7f93911f00d6a47f7972667df/src/controller/controller.ts#L237-L239

To solve this https://github.com/madchicken/homebridge-zigbee-nt/blob/0a1b568d2a7c4120cdce7ecef207536b356ce2b2/src/zigbee/zigBee-controller.ts#L126 cannot be null, a `{ }` may help.

---
Please consider locking the version for unstable dependencies.

**Comment by tutasca** [comment]
Where do i find this file to modify it?
homebridge-zigbee-nt/src/zigbee/zigBee-controller.ts

**Comment by manuchis** [comment]
Same here, now I cannot pair my devices after reinstall.

**Comment by madchicken** [comment]
Sorry, I didn't't get notifications from GitHub about recent issues so I lost this one 🤷‍♂️
I'll fix the issue in the next few days
