### ISSUE TITLE
Devices not registered and therefore missing in RC3

### ISSUE THREAD

**Issue by bcharbonnier** [madchicken/homebridge-zigbee-nt#17]
I have noticed a very weird thing after updating to RC3.
My `LUMI lumi.weather` devices are not working anymore.
They appear to be _not recognised_ in the log when the plugin try to load them from the database.

After investigation, I discovered that the RC3 published on npm is missing a lot of devices!!
This is the `index.js` published on npm -> https://unpkg.com/homebridge-zigbee-nt@1.0.0-rc.3/dist/index.js

It does not correspond at all to what is on `master`.
For example, all these ones are missing
```
registerAccessoryClass('GLEDOPTO', ['GL-C-009'], GledoptoDim);
registerAccessoryClass('LUMI', ['lumi.weather', 'lumi.sensor_ht.agl02'], TempHumiSensor);
registerAccessoryClass('Xiaomi', ['MCCGQ01LM'], XiaomiContactSensor);
registerAccessoryClass('LUMI', ['lumi.sensor_magnet'], XiaomiContactSensor);
registerAccessoryClass('Xiaomi', ['GZCGQ01LM'], XiaomiLightIntensitySensor);
registerAccessoryClass('LUMI', ['lumi.sen_ill.mgl01'], XiaomiLightIntensitySensor);
registerAccessoryClass('TuYa', ['GDKES-02TZXD'], TuyaOnoffDoubleSwitch);
```

What I can't explain is that these devices are also not present neither in `rc2` where they should have been introduced with https://github.com/madchicken/homebridge-zigbee-nt/pull/9

**Comment by madchicken** [comment]
Ok, this is absolutely weird. I will investigate

**Comment by madchicken** [comment]
Should be fixed in RC4. Please check it.
