### ISSUE TITLE
aqara window sensor 

### ISSUE THREAD

**Issue by 5edenmeiri** [madchicken/homebridge-zigbee-nt#172]
hey. 
so i have the Zigbee stick connected to the homebridge. 
when i install your plugin and switch on the permit join I see a temperature sensor instead of a window sensor. 
however, on homebridge i do see a window sensor close but when i open the sensor its not responding. 

my question is - 
why do I see a temperature sensor? (i don't have one) 
how can i make the window sensor work properly? 
thank you

**Comment by 5edenmeiri** [comment]
???

**Comment by madchicken** [comment]
@5edenmeiri let me know if you can find the device JSON descriptor
