### ISSUE TITLE
Trådfri bulbs - no smooth transitions / dimming

### ISSUE THREAD

**Issue by Jannomag** [madchicken/homebridge-zigbee-nt#178]
Hi,
I just got homebridge on my raspberry pi home server running and installed this plugin. 
I added 3 IKEA Trådfri E14 bulbs (TRADFRI bulb E14 WS 470lm) and they're working "fine".

I noticed that they don't dim or fade smoothly. Especially when changing colors it's happening without any transition.

I also noticed that they are changing their states (color, dim, on/off) not together as they do with the dim switch from IKEA. There's a small delay between each bulb.

Is there any way to fix those things, especially the transitions with this plugin?

**Comment by madchicken** [comment]
@Jannomag could you try adding this to your plugin configuration for your bulb(s)?
```
            "customDeviceSettings": [
                {
                    "ieeeAddr": "DEVICE_IEEE_ADDR",
                    "friendlyName": "A CUSTOM NAME",
                    "transition": true
                }
             ]

```

**Comment by Jannomag** [comment]
Somehow the homebridge installation crashed my whole raspberry and I was not able to recover the system even using my backup files. So I needed to reinstall it completely and gave up on this project. 
anyways, thanks for the reply
