### ISSUE TITLE
cannot update to version 2.5.0

### ISSUE THREAD

**Issue by Figo66** [madchicken/homebridge-zigbee-nt#179]
npm ERR! code ERESOLVE idealTree:homebridge-zigbee-nt: sill placeDep ROOT homebridge-zigbee-nt@2.5.0 OK for:  want: 2.5.0
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! Found: react@17.0.2
npm ERR! node_modules/homebridge-zigbee-nt/node_modules/react
npm ERR!   react@"17.0.2" from homebridge-zigbee-nt@2.5.0
npm ERR!   node_modules/homebridge-zigbee-nt
npm ERR!     homebridge-zigbee-nt@"2.5.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^15.3.0 || ^16.0.0" from react-event-listener@0.5.10
npm ERR! node_modules/homebridge-zigbee-nt/node_modules/evergreen-ui/node_modules/react-event-listener
npm ERR!   react-event-listener@"^0.5.1" from react-scrollbar-size@2.1.0
npm ERR!   node_modules/homebridge-zigbee-nt/node_modules/evergreen-ui/node_modules/react-scrollbar-size
npm ERR!     react-scrollbar-size@"^2.0.2" from evergreen-ui@5.1.2
npm ERR!     node_modules/homebridge-zigbee-nt/node_modules/evergreen-ui
npm ERR!       evergreen-ui@"5.1.2" from homebridge-zigbee-nt@2.5.0
npm ERR!       node_modules/homebridge-zigbee-nt
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/homebridge/.npm/eresolve-report.txt for a full report.
[..................] - idealTree:homebridge-zigbee-nt: sill placeDep ROOT homebridge-zigbee-nt@2.5.0 OK for:  want: 2.5.0
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/homebridge/.npm/_logs/2021-07-27T16_12_17_903Z-debug.log

Command failed. Please review log for details.

**Comment by madchicken** [comment]
Should be fixed in #2.5.1
