### ISSUE TITLE
Brightness percentage not reported correctly

### ISSUE THREAD

**Issue by yannishuber** [madchicken/homebridge-zigbee-nt#195]
There seems to be an issue with the reported brightness in Homebridge. Setting a brightness value from the Apple Home app does update the light bulb's brightness as expected, however, the reported brightness which is read back after by the Home app is always 100%. (The same occurs if the brightness is updated from the Homebridge dashboard.)

Plugin version: 2.5.2
Light bulb: TRADFRI bulb E27 WW clear 250lm

```
[20/09/2021, 17:25:45] [ZigBee] Updating state of device Bed with  {}
[20/09/2021, 17:25:45] [ZigBee] Updated state for device Bed is now  { state: 'ON', brightness_percent: 100, brightness: 38 }
```

**Comment by madchicken** [comment]
Uhm, it seems a problem in the herdsman lib when reporting the percentage. I should problem use the non converted value and convert manually to %

**Comment by yannishuber** [comment]
This issue is still persisting in version 2.5.5.
