### ISSUE TITLE
Ikea shortcut button fw 2.3.80 button presses not registering

### ISSUE THREAD

**Issue by britishchris** [madchicken/homebridge-zigbee-nt#212]
Hi,
I have several ikea Shortcut butttons, some are running firmware 2.3.15 and these work with this plug-in. However, some are firmware 2.3.80 which was recently released. These buttons pair OK and are visible in HomeKit, but the button presses do not register. 
Is it possible to update in order to support the newer firmware? 

Is there any details you require me to send?

Thanks in advance

**Comment by madchicken** [comment]
It would be good if you could attach the log of HB when you press the button

**Comment by britishchris** [comment]
[homebridge-shortcut-button-2.3.80-log.txt](https://github.com/madchicken/homebridge-zigbee-nt/files/7687421/homebridge-shortcut-button-2.3.80-log.txt)
[zigbee-structure-shortcut-2.3.80.txt](https://github.com/madchicken/homebridge-zigbee-nt/files/7687422/zigbee-structure-shortcut-2.3.80.txt)

Hi, I'm attaching two files. the first is when I pair the Shortcut button with Homebridge. The second one is the 'Structure' from the ZigbeeNT WebUI.

There is no change to the log file when I press the button after pairing it. 
Does it help?

**Comment by madchicken** [comment]
Ok, I found out is a bug with the new firmware, that can be solved by binding the on/off endpoint to the coordinator: https://github.com/Koenkk/zigbee2mqtt/issues/9551
The problem is that you can't do that ATM from the plugin UI, I need to add that feature 😞
