### ISSUE TITLE
Is there any planned support for CC2652P?

### ISSUE THREAD

**Issue by jmaferreira** [madchicken/homebridge-zigbee-nt#218]
Hi,

I read good things about the Sonoff USB dongle with the CC2652P chipset (https://sonoff.tech/product/diy-smart-switch/sonoff-dongle-plus).

Does this plugin supports this dongle or will it in the future?

Cheers.

**Comment by madchicken** [comment]
I use the same library Zigbee2MQTT is using to connect to the adapter, so all the adapters listed here should be supported: https://www.zigbee2mqtt.io/guide/adapters/#notes

It seems yours is there, so it should work. If it doesn't send me the logs from HB when you start the plugin
