### ISSUE TITLE
Add support for Philips Hue Go (v2) and ST72 Bulbs

### ISSUE THREAD

**Issue by britishchris** [madchicken/homebridge-zigbee-nt#224]
Hi, 
Is it possible to add support for the following Hue products? The logs show that the devices are unsupported.

Philips Hue Go (v2): https://www.lighting.philips.co.uk/consumer/choose-a-fixture/hue-go
**Model Number 7602031PU** 
[Hue Go 7602031PU.txt](https://github.com/madchicken/homebridge-zigbee-nt/files/7809040/Hue.Go.7602031PU.txt)

Philips Hue White Filament ST72 https://www.philips-hue.com/en-gb/p/hue-white-filament-1-pack-st72-b22-filament-edison/8719514279193 **Model Number LWV004**
[Philips LWV004.txt](https://github.com/madchicken/homebridge-zigbee-nt/files/7809034/Philips.LWV004.txt)

Thanks in advance!

**Comment by madchicken** [comment]
@britishchris any news on this issue?
