### ISSUE TITLE
Blank Screen in Zigbee Web Gui with version 2.5.8

### ISSUE THREAD

**Issue by maccoylton** [madchicken/homebridge-zigbee-nt#241]
After installing the latest version I get a blank screen when trying to access the zigbee gui on port 9000. Running on Raspberry Pi bullseye.  A remove and re-install didn't fix this . 

See screensot attached
[Zigbee Web Error.pdf](https://github.com/madchicken/homebridge-zigbee-nt/files/8710255/Zigbee.Web.Error.pdf)

**Comment by archiolochos** [comment]
same here!

**Comment by jmaferreira** [comment]
Is happening to me as well!

**Comment by Stevethebeef** [comment]
Same for me 😅

**Comment by simon3789** [comment]
Same here
