### ISSUE TITLE
Devices supported before update no longer supported

### ISSUE THREAD

**Issue by magnetarhotelrwanda** [madchicken/homebridge-zigbee-nt#244]
So I have updated from v2.5.7 to v2.5.8 and had to roll back due to the "uri-js" bug. However devices that were supported before this are now reported as not supported and cant be added.

The devices in question are SONOFF ZBMINI-L which worked perfectly fine before doing the update then rolling back.

`
[28/06/2022, 13:27:38] [ZigBee] Initializing ZigBee device: 0x00124b0026b753c7 - ZBMINI-L - SONOFF

[28/06/2022, 13:27:38] [ZigBee] Unsupported ZigBee device: 0x00124b0026b753c7 - ZBMINI-L - SONOFF

[28/06/2022, 13:27:38] [ZigBee] Device not recognized:  {
  device: Device {
    ID: 2,
    _type: 'EndDevice',
    _ieeeAddr: '0x00124b0026b753c7',
    _networkAddress: 49595,
    _manufacturerID: 4742,
    _endpoints: [ [Endpoint] ],
    _manufacturerName: 'SONOFF',
    _powerSource: 'Mains (single phase)',
    _modelID: 'ZBMINI-L',
    _applicationVersion: 2,
    _stackVersion: undefined,
    _zclVersion: 3,
    _hardwareVersion: 1,
    _dateCode: '20220121',
    _softwareBuildID: '1.0.5',
    _interviewCompleted: true,
    _interviewing: false,
    _skipDefaultResponse: false,
    _skipTimeResponse: false,
    meta: {},
    _lastSeen: 1656422857630,
    _defaultSendWhenActive: true,
    useImplicitCheckin: false,
    _linkquality: 36
  }
}
`

More Info:
Node.js Version - v16.15.1
Homebridge Version - v1.5.0
Homebridge-Zigbee-nt Version - v2.5.7
OS - Ubuntu 22.04 LTS

**Comment by madchicken** [comment]
This is probably due to a change in the zigbee converters lib. I'll take a look

**Comment by madchicken** [comment]
I tested locally, and it seems to be correctly configured as a switch. Maybe it's cached by homebridge? Can you try to remove the cache key for that accessory? You should go under Homebridge settings and click on `Remove Single Cached Accessory`, then find the accessory (should be somryhing like `0x00124b0026b753c7 (homebridge-zigbee-nt)`). After deleting you have to restart homebridge

**Comment by madchicken** [comment]
Closing since inactivity. Feel free to reopen
