### ISSUE TITLE
Please add button Aqara and Magic Cude Aqara

### ISSUE THREAD

**Issue by xrust83** [madchicken/homebridge-zigbee-nt#29]
[log.txt](https://github.com/madchicken/homebridge-zigbee-nt/files/5219698/log.txt)

**Comment by xrust83** [comment]
I use a stick from aliexpress https://aliexpress.ru/item/4000816404730.html
I see responses to device responses. Perhaps for normal operation it needs to be reflashed or updated?

**Comment by xrust83** [comment]
[zigbee log.txt](https://github.com/madchicken/homebridge-zigbee-nt/files/5229954/zigbee.log.txt)

**Comment by madchicken** [comment]
The device pairs but it is not recognised by the plugin (i.e. not mapped by any accessory). Should be fairly easy to add it

**Comment by tutasca** [comment]
Same here with aqara opple 4 buttons. Really cheap buttons  https://www.aliexpress.com/i/4000317941888.html
. Log looks identical
I have no coding skills. 
Please help. 

;)

[10/16/2020, 10:12:05] [ZigB] No device found from message {
  type: 'commandStep',
  device: Device {
    ID: 4,
    _type: 'EndDevice',
    _ieeeAddr: '0x04cf8cdf3c792af9',
    _networkAddress: 18507,
    _manufacturerID: 4447,
    _endpoints: [ [Endpoint] ],
    _manufacturerName: 'LUMI',
    _powerSource: 'Battery',
    _modelID: 'lumi.remote.b486opcn01',
    _applicationVersion: 17,
    _stackVersion: 2,
    _zclVersion: 3,
    _hardwareVersion: 1,
    _dateCode: '20190730',
    _softwareBuildID: '2019\u0000www.',
    _interviewCompleted: true,
    _interviewing: false,
    meta: {},
    _lastSeen: 1602839525698
  },
  endpoint: Endpoint {
    ID: 1,
    profileID: 260,
    deviceID: 261,
    inputClusters: [ 0, 3, 1 ],
    outputClusters: [ 3, 6, 8, 768 ],
    deviceNetworkAddress: 18507,
    deviceIeeeAddress: '0x04cf8cdf3c792af9',
    clusters: { genBasic: [Object] },
    _binds: []
  },
  data: { stepmode: 1, stepsize: 85, transtime: 7 },
  linkquality: 0,
  groupID: 0,
  cluster: 'genLevelCtrl',
  meta: {
    zclTransactionSequenceNumber: 17,
    manufacturerCode: null,
    frameControl: {
      frameType: 1,
      manufacturerSpecific: false,
      direction: 0,
      disableDefaultResponse: true,
      reservedBits: 0
    }
  }
}
[10/16/2020, 10:12:05] [ZigB] No device found from message {
  type: 'commandStep',
  device: Device {
    ID: 4,
    _type: 'EndDevice',
    _ieeeAddr: '0x04cf8cdf3c792af9',
    _networkAddress: 18507,
    _manufacturerID: 4447,
    _endpoints: [ [Endpoint] ],
    _manufacturerName: 'LUMI',
    _powerSource: 'Battery',
    _modelID: 'lumi.remote.b486opcn01',
    _applicationVersion: 17,
    _stackVersion: 2,
    _zclVersion: 3,
    _hardwareVersion: 1,
    _dateCode: '20190730',
    _softwareBuildID: '2019\u0000www.',
    _interviewCompleted: true,
    _interviewing: false,
    meta: {},
    _lastSeen: 1602839525707
  },
  endpoint: Endpoint {
    ID: 1,
    profileID: 260,
    deviceID: 261,
    inputClusters: [ 0, 3, 1 ],
    outputClusters: [ 3, 6, 8, 768 ],
    deviceNetworkAddress: 18507,
    deviceIeeeAddress: '0x04cf8cdf3c792af9',
    clusters: { genBasic: [Object] },
    _binds: []
  },
  data: { stepmode: 1, stepsize: 85, transtime: 7 },
  linkquality: 0,
  groupID: 0,
  cluster: 'genLevelCtrl',
  meta: {
    zclTransactionSequenceNumber: 17,
    manufacturerCode: null,
    frameControl: {
      frameType: 1,
      manufacturerSpecific: false,
      direction: 0,
      disableDefaultResponse: true,
      reservedBits: 0
    }
  }
}
[10/16/2020, 10:12:05] [ZigB] No device found from message {
  type: 'commandStep',
  device: Device {
    ID: 4,
    _type: 'EndDevice',
    _ieeeAddr: '0x04cf8cdf3c792af9',
    _networkAddress: 18507,
    _manufacturerID: 4447,
    _endpoints: [ [Endpoint] ],
    _manufacturerName: 'LUMI',
    _powerSource: 'Battery',
    _modelID: 'lumi.remote.b486opcn01',
    _applicationVersion: 17,
    _stackVersion: 2,
    _zclVersion: 3,
    _hardwareVersion: 1,
    _dateCode: '20190730',
    _softwareBuildID: '2019\u0000www.',
    _interviewCompleted: true,
    _interviewing: false,
    meta: {},
    _lastSeen: 1602839525714
  },
  endpoint: Endpoint {
    ID: 1,
    profileID: 260,
    deviceID: 261,
    inputClusters: [ 0, 3, 1 ],
    outputClusters: [ 3, 6, 8, 768 ],
    deviceNetworkAddress: 18507,
    deviceIeeeAddress: '0x04cf8cdf3c792af9',
    clusters: { genBasic: [Object] },
    _binds: []
  },
  data: { stepmode: 1, stepsize: 85, transtime: 7 },
  linkquality: 0,
  groupID: 0,
  cluster: 'genLevelCtrl',
  meta: {
    zclTransactionSequenceNumber: 17,
    manufacturerCode: null,
    frameControl: {
      frameType: 1,
      manufacturerSpecific: false,
      direction: 0,
      disableDefaultResponse: true,
      reservedBits: 0
    }
  }
}
[10/16/2020, 10:12:05] [ZigB] No device found from message {
  type: 'commandStep',
  device: Device {
    ID: 4,
    _type: 'EndDevice',
    _ieeeAddr: '0x04cf8cdf3c792af9',
    _networkAddress: 18507,
    _manufacturerID: 4447,
    _endpoints: [ [Endpoint] ],
    _manufacturerName: 'LUMI',
    _powerSource: 'Battery',
    _modelID: 'lumi.remote.b486opcn01',
    _applicationVersion: 17,
    _stackVersion: 2,
    _zclVersion: 3,
    _hardwareVersion: 1,
    _dateCode: '20190730',
    _softwareBuildID: '2019\u0000www.',
    _interviewCompleted: true,
    _interviewing: false,
    meta: {},
    _lastSeen: 1602839525720
  },
  endpoint: Endpoint {
    ID: 1,
    profileID: 260,
    deviceID: 261,
    inputClusters: [ 0, 3, 1 ],
    outputClusters: [ 3, 6, 8, 768 ],
    deviceNetworkAddress: 18507,
    deviceIeeeAddress: '0x04cf8cdf3c792af9',
    clusters: { genBasic: [Object] },
    _binds: []
  },
  data: { stepmode: 1, stepsize: 85, transtime: 7 },
  linkquality: 0,
  groupID: 0,
  cluster: 'genLevelCtrl',
  meta: {
    zclTransactionSequenceNumber: 17,
    manufacturerCode: null,
    frameControl: {
      frameType: 1,
      manufacturerSpecific: false,
      direction: 0,
      disableDefaultResponse: true,
      reservedBits: 0
    }
  }
}
[10/16/2020, 10:12:05] [ZigB] No device found from message {
  type: 'commandStep',
  device: Device {
    ID: 4,
    _type: 'EndDevice',
    _ieeeAddr: '0x04cf8cdf3c792af9',
    _networkAddress: 18507,
    _manufacturerID: 4447,
    _endpoints: [ [Endpoint] ],
    _manufacturerName: 'LUMI',
    _powerSource: 'Battery',
    _modelID: 'lumi.remote.b486opcn01',
    _applicationVersion: 17,
    _stackVersion: 2,
    _zclVersion: 3,
    _hardwareVersion: 1,
    _dateCode: '20190730',
    _softwareBuildID: '2019\u0000www.',
    _interviewCompleted: true,
    _interviewing: false,
    meta: {},
    _lastSeen: 1602839525728
  },
  endpoint: Endpoint {
    ID: 1,
    profileID: 260,
    deviceID: 261,
    inputClusters: [ 0, 3, 1 ],
    outputClusters: [ 3, 6, 8, 768 ],
    deviceNetworkAddress: 18507,
    deviceIeeeAddress: '0x04cf8cdf3c792af9',
    clusters: { genBasic: [Object] },
    _binds: []
  },
  data: { stepmode: 1, stepsize: 85, transtime: 7 },
  linkquality: 0,
  groupID: 0,
  cluster: 'genLevelCtrl',
  meta: {
    zclTransactionSequenceNumber: 17,
    manufacturerCode: null,
    frameControl: {
      frameType: 1,
      manufacturerSpecific: false,
      direction: 0,
      disableDefaultResponse: true,
      reservedBits: 0
    }
  }
}
[10/16/2020, 10:12:05] [ZigB] No device found from message {
  type: 'commandStep',
  device: Device {
    ID: 4,
    _type: 'EndDevice',
    _ieeeAddr: '0x04cf8cdf3c792af9',
    _networkAddress: 18507,
    _manufacturerID: 4447,
    _endpoints: [ [Endpoint] ],
    _manufacturerName: 'LUMI',
    _powerSource: 'Battery',
    _modelID: 'lumi.remote.b486opcn01',
    _applicationVersion: 17,
    _stackVersion: 2,
    _zclVersion: 3,
    _hardwareVersion: 1,
    _dateCode: '20190730',
    _softwareBuildID: '2019\u0000www.',
    _interviewCompleted: true,
    _interviewing: false,
    meta: {},
    _lastSeen: 1602839525735
  },
  endpoint: Endpoint {
    ID: 1,
    profileID: 260,
    deviceID: 261,
    inputClusters: [ 0, 3, 1 ],
    outputClusters: [ 3, 6, 8, 768 ],
    deviceNetworkAddress: 18507,
    deviceIeeeAddress: '0x04cf8cdf3c792af9',
    clusters: { genBasic: [Object] },
    _binds: []
  },
  data: { stepmode: 1, stepsize: 85, transtime: 7 },
  linkquality: 0,
  groupID: 0,
  cluster: 'genLevelCtrl',
  meta: {
    zclTransactionSequenceNumber: 17,
    manufacturerCode: null,
    frameControl: {
      frameType: 1,
      manufacturerSpecific: false,
      direction: 0,
      disableDefaultResponse: true,
      reservedBits: 0
    }
  }
}

**Comment by xrust83** [comment]
Update 1.0.5 did not affect the issue in any way
[10/16/2020, 13:38:12] [ZigBee] Zigbee message from 0x00158d0002a37354 attributeReport
[10/16/2020, 13:38:12] [ZigBee] No device found from message {
  type: 'attributeReport',
  device: Device {
    ID: 4,
    _type: 'EndDevice',
    _ieeeAddr: '0x00158d0002a37354',
    _networkAddress: 61542,
    _manufacturerID: 4151,
    _endpoints: [ [Endpoint], [Endpoint], [Endpoint] ],
    _manufacturerName: 'LUMI',
    _powerSource: 'Battery',
    _modelID: 'lumi.sensor_cube.aqgl01',
    _applicationVersion: 5,
    _stackVersion: 2,
    _zclVersion: 1,
    _hardwareVersion: 1,
    _dateCode: '20160704',
    _softwareBuildID: '3000-0001',
    _interviewCompleted: true,
    _interviewing: false,
    meta: {},
    _lastSeen: 1602844692903
  },
  endpoint: Endpoint {
    ID: 1,
    profileID: 260,
    deviceID: 24321,
    inputClusters: [ 0, 3, 25, 18 ],
    outputClusters: [ 0, 4, 3, 5, 25, 18 ],
    deviceNetworkAddress: 61542,
    deviceIeeeAddress: '0x00158d0002a37354',
    clusters: { genBasic: [Object] },
    _binds: []
  },
  data: {
    '65281': {
      '1': 2855,
      '3': 23,
      '4': 5032,
      '5': 206,
      '6': [Array],
      '10': 0,
      '151': 0,
      '152': 10,
      '153': 7,
      '154': 4
    },
    modelId: 'lumi.sensor_cube.aqgl01'
  },
  linkquality: 52,
  groupID: 0,
  cluster: 'genBasic',
  meta: {
    zclTransactionSequenceNumber: 9,
    manufacturerCode: 4447,
    frameControl: {
      frameType: 0,
      manufacturerSpecific: true,
      direction: 1,
      disableDefaultResponse: true,
      reservedBits: 0
    }
  }
}

**Comment by xrust83** [comment]
[ZigBee] Found ZigBee device:  Device {
  ID: 5,
  _type: 'EndDevice',
  _ieeeAddr: '0x00158d00020442d7',
  _networkAddress: 20311,
  _manufacturerID: 4151,
  _endpoints: [
    Endpoint {
      ID: 1,
      profileID: undefined,
      deviceID: undefined,
      inputClusters: [],
      outputClusters: [],
      deviceNetworkAddress: 20311,
      deviceIeeeAddress: '0x00158d00020442d7',
      clusters: [Object],
      _binds: []
    }
  ],
  _manufacturerName: undefined,
  _powerSource: undefined,
  _modelID: 'lumi.sensor_switch.aq2',
  _applicationVersion: 3,
  _stackVersion: undefined,
  _zclVersion: undefined,
  _hardwareVersion: undefined,
  _dateCode: undefined,
  _softwareBuildID: undefined,
  _interviewCompleted: false,
  _interviewing: true,
  meta: {},
  _lastSeen: 1602845083752
}
[10/16/2020, 13:44:45] [ZigBee] Unrecognized device: 0x00158d00020442d7 undefined lumi.sensor_switch.aq2

**Comment by madchicken** [comment]
It seems it is registered with the wrong implementation class. I'll take a look
