### ISSUE TITLE
Feature: Add ability for "power points" to be displayed as “switches"

### ISSUE THREAD

**Issue by EdwardChamberlain** [madchicken/homebridge-zigbee-nt#30]
Currently I can set my ikea sockets to be displayed as power points, fans, or lights. It would be nice to have them be able to work as switches too. I dont know if this is a HomeKit limitation.

**Comment by madchicken** [comment]
Unfortunately yes, it's an Homekit limitation. I don't have a way to modify how the app shows accessories I map

**Comment by EdwardChamberlain** [comment]
Is there an option to change how it maps? e.g. map to switch rather than socket?

**Comment by madchicken** [comment]
Te only way is to create a switch accessory from Homebridge
