### ISSUE TITLE
Lonsonho X712A

### ISSUE THREAD

**Issue by tomerakower** [madchicken/homebridge-zigbee-nt#33]
Sep 26 15:13:40 homebridge npm[27035]: Zigbee2MQTT:info  2020-09-26 15:13:40: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_successful","meta":{"description":"Smart light switch - 2 gang without neutral wire","friendly_name":"0xbc33acfffe62ef4e","model":"TS0012","supported":true,"vendor":"TuYa"},"type":"pairing"}'
Sep 26 15:13:40 homebridge npm[27035]: Zigbee2MQTT:info  2020-09-26 15:13:40: Successfully configured '0xbc33acfffe62ef4e'

please add this model: Lonsonho X712A

**Comment by madchicken** [comment]
I'll try to work on this. Sorry I am very busy in this period...

**Comment by madchicken** [comment]
version v1.0.8 should fix this
