### ISSUE TITLE
Cannot Configure Device (ikea ON/OFF button)

### ISSUE THREAD

**Issue by wamfox** [madchicken/homebridge-zigbee-nt#36]
This seems to be an issue with the ikea steering devices. They work but print this message in the log:

![image](https://user-images.githubusercontent.com/72502560/95583866-23f0b000-0a80-11eb-9202-1ccfedde7cfe.png)

 The device will sometimes be unresponsive to input for a few clicks as homebridge-zigbee-nt remounts the device

**Comment by wamfox** [comment]
The unresponsiveness does seem to be fixed after a re-pair. But the error message persists.

**Comment by noyer17** [comment]
Same here with same device. After first device pairing, everything works fine. I can assign single press/long press of both buttons. But after some time, I get message again, that button was just configured again. And from now, only one button is working, and not stable/not all the time.

Any idea why device is trying to configure again and again ?

**Comment by madchicken** [comment]
I know that device goes in a sort of sleep mode after a bit, and sometime I have to click it two three times before awake it and make it work again. I am still investigating

**Comment by madchicken** [comment]
This should be fixed now. The remaining problem is to avoid the button to go in sleep mode...
