### ISSUE TITLE
[feature] Elgato Eve history support?

### ISSUE THREAD

**Issue by mrdc** [madchicken/homebridge-zigbee-nt#39]
Hello,

Would be nice to have Elgato Eve history support like in abandoned homebridge-zigbee plugin.

Source is here:
https://github.com/simont77/fakegato-history

**Comment by madchicken** [comment]
This is something I am thinking about from a while...but I am essentially alone developing this plugin, so you need to wait unless someone is gonna open a PR here 😄

**Comment by Kristian8606** [comment]
I would help! I have working test code in my TypeScript repository

**Comment by madchicken** [comment]
@Kristian8606 can you open a PR? It would be very appreciated

**Comment by Kristian8606** [comment]
I did not understand your question! Sorry for my bad English.

**Comment by madchicken** [comment]
PR = Pull Request
Please read this https://docs.github.com/en/enterprise/2.16/user/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request

**Comment by madchicken** [comment]
Even better, start from here: https://docs.github.com/en/enterprise/2.16/user/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork

**Comment by Kristian8606** [comment]
Yes, I understand your question now.

**Comment by Kristian8606** [comment]
Here is a link to my test code

https://github.com/Kristian8606/Test/blob/3c0a9c64ac37304f1d2051e5840cedca468166f9/src/platformAccessory.ts#L97-L111
