### ISSUE TITLE
Request new device Aqara opple button

### ISSUE THREAD

**Issue by tutasca** [madchicken/homebridge-zigbee-nt#40]
Hi.
Sorry as I posted this on another thread
Can you add support for this opple wireless button?
https://www.aliexpress.com/i/4000317941888.html
Thanks

**Comment by tr1ng0** [comment]
Would love to see that device added aswell! 
@tutasca did you find something to integrate the button to Homebridge/Homekit?

**Comment by tutasca** [comment]
No. I tried different approaches and I finally retuned it.
