### ISSUE TITLE
Ikea Tradfri Motion Sensor

### ISSUE THREAD

**Issue by HA-Lemme** [madchicken/homebridge-zigbee-nt#47]
Hey all, 

I recently bought an Ikea Tradfri Motion Sensor, I paired it without any issues, but it seems to not detect anything! Is there a known issue?

regards

**Comment by noyer17** [comment]
Same here :(

**Comment by Chennyisafrag** [comment]
Same as well, all 3 of mine... buying an aqara motion sensor to see if it's just the IKEA ones.

**Comment by noyer17** [comment]
@Chennyisafrag I bought it also, and it seems that it is not supported yet by this plugin. Check this: [thread](https://github.com/madchicken/homebridge-zigbee-nt/issues/54).

**Comment by madchicken** [comment]
Version v1.0.8 should fix this. Feel free to reopen the issue if you still have problems
