### ISSUE TITLE
Can't Install the Plugin in Docker Image

### ISSUE THREAD

**Issue by AlexKusnezov** [madchicken/homebridge-zigbee-nt#48]
Hey guys, 
I run hb in docker-.compose. When I try to install the plugin, it goes through the installation process but nothing shows up in the Plugins section when it's completed.
Any idea why?
btw I'm on homebridge version 1.2.4, here's ym config file:
```version: '2'
services:
  homebridge:
    image: oznu/homebridge:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PGID=1000
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=9090
    volumes:
      - /mnt/homebridge:/homebridge
```

**Comment by madchicken** [comment]
Could you check if the zigbee database gets created under `/mnt/homebridge`?

**Comment by AlexKusnezov** [comment]
@madchicken 
>Could you check if the zigbee database gets created under /mnt/homebridge?

No, it's not. Just tried it again.

**Comment by madchicken** [comment]
Could you activate DEBUG (in homebridge settings section of UI) and attach homebridge logs here?

**Comment by AlexKusnezov** [comment]
@madchicken there was nothing in the logs, just information about already installed plugins. I tried to run the installation from terminal within homebridge with ```npm install --save homebridge-zigbee-nt@latest --loglevel verbose``` but it just resulted in restart of the homebridge itself

**Comment by madchicken** [comment]
It's really hard to understand what's going on without any output. Are you using a raspberry Pi?
Please, drop some detail about your system, so I can try to reproduce this issue

**Comment by AlexKusnezov** [comment]
@madchicken 
Architecture (Ex: x86, ARM): armv7
Docker image version: oznu/homebridge:latest
OS (Ex: Windows 10, Ubuntu Buster): Raspberry Pi OS Buster
Hardware (Ex: PC, Raspberry Pi 1/2/3/Zero): Raspberry Pi 3 B+

I try to install it lile every other plugin, but it just doesn't appear under plugins after the Installation. When I'm back on my machine I will screen capture the process and forward it to you. This would be at least something. My full docker-compose config I posted above.

**Comment by AlexKusnezov** [comment]
@madchicken here I screen-captured the installation process:
https://drive.google.com/file/d/1QgH6NbDCDu_ALVMwOLNr892PNdgTopZd/view?usp=sharing

you can see, that the plugin doesn't appear after install is complete

**Comment by madchicken** [comment]
To me it seems that the process is taking a lot to complete and homebridge UI is killing the process. Can you try to run the same command from a SSH shell?

**Comment by AlexKusnezov** [comment]
@madchicken thank you so much for the hint. I've just installed it successfully via homebridge terminal
