### ISSUE TITLE
Xiaomi motion sensor - RTCGQ01LM

### ISSUE THREAD

**Issue by mcruscher** [madchicken/homebridge-zigbee-nt#49]
Hello,

I added the Xiaomi motion sensor an it is working partly. I based it on the ikea motion sensor. The occupancy is reported and also exposed in Homebridge. But I can not find a way to set the time-out of the occupancy. Also battery report is not exposed correctly.

Anyone who can help?

"use strict";
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.xiaomiMotionSensor = void 0;
const zig_bee_accessory_1 = require("../zig-bee-accessory");
class xiaomiMotionSensor extends zig_bee_accessory_1.ZigBeeAccessory {
    getAvailableServices() {
        const Service = this.platform.api.hap.Service;
        const Characteristic = this.platform.api.hap.Characteristic;
        this.sensorService =
            this.accessory.getService(Service.MotionSensor) ||
                this.accessory.addService(Service.MotionSensor);
        this.sensorService.setCharacteristic(Characteristic.Name, this.name);
        this.sensorService
            .getCharacteristic(Characteristic.MotionDetected)
            .on("get" /* GET */, (callback) => __awaiter(this, void 0, void 0, function* () {
            if (this.state.occupancy) {
                this.log.debug(`Motion detected for sensor ${this.name}`);
            }
            callback(null, this.state.occupancy);
        }));
        this.sensorService
            .getCharacteristic(Characteristic.StatusLowBattery)
            .on("get" /* GET */, (callback) => __awaiter(this, void 0, void 0, function* () {
            callback(null, this.state.battery && this.state.battery <= 10
                ? Characteristic.StatusLowBattery.BATTERY_LEVEL_LOW
                : Characteristic.StatusLowBattery.BATTERY_LEVEL_NORMAL);
        }));
        return [this.sensorService];
    }
    update(device, state) {
        super.update(device, state);
        const Characteristic = this.platform.api.hap.Characteristic;
        this.sensorService.updateCharacteristic(this.platform.Characteristic.MotionDetected, state.occupancy);
        this.sensorService.updateCharacteristic(this.platform.Characteristic.StatusLowBattery, state.battery && state.battery <= 10
            ? Characteristic.StatusLowBattery.BATTERY_LEVEL_LOW
            : Characteristic.StatusLowBattery.BATTERY_LEVEL_NORMAL);
    }
}
exports.xiaomiMotionSensor = xiaomiMotionSensor;
//# sourceMappingURL=xiaomi-motion-sensor.js.map

**Comment by madchicken** [comment]
Could you open a PR with your code so I can take a look?

**Comment by madchicken** [comment]
Could you try version 1.0.8? It have support for this sensor
