### ISSUE TITLE
Ikea ON/OFF appears by default

### ISSUE THREAD

**Issue by manuchis** [madchicken/homebridge-zigbee-nt#5]
Hi again, in the rc1 the Ikea ON/OFF accesory appears by default and then the logs show errors because there is no connection to the devices ( obviously ). Is there a way to deactivate it ?

Thanks again for great work and improvements!

**Comment by madchicken** [comment]
This is absolutely weird. Can you check the content of the zigbee database? The platform should only map the devices registered in the db...

**Comment by manuchis** [comment]
Here it is: 
`{"id":2,"type":"EndDevice","ieeeAddr":"0x14b457fffec8d738","nwkAddr":21286,"manufId":4476,"manufName":"IKEA of Sweden","powerSource":"Battery","modelId":"TRADFRI on/off switch","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":2080,"inClusterList":[0,1,3,9,32,4096,64636],"outClusterList":[3,4,6,8,25,258,4096],"clusters":{"genBasic":{"attributes":{"modelId":"TRADFRI on/off switch","manufacturerName":"IKEA of Sweden","powerSource":3,"zclVersion":3,"appVersion":34,"stackVersion":98,"hwVersion":1,"dateCode":"20190410","swBuildId":"2.2.008"}}},"binds":[]}},"appVersion":34,"stackVersion":98,"hwVersion":1,"dateCode":"20190410","swBuildId":"2.2.008","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1593802671178}`

Maybe is an old device that I tried to sync and I forgot about.

**Comment by madchicken** [comment]
try deleting it from the database, is should work (you probably need to remove it also from Homebridge cache). Btw, there is no easy way to remove devices, I know...

**Comment by manuchis** [comment]
Done, sorry I thought that it was related to the update.
