### ISSUE TITLE
Supporting new device Aqara Water Leak Sensor SJCGQ11LM

### ISSUE THREAD

**Issue by madmarf** [madchicken/homebridge-zigbee-nt#53]
Hello,

paired the sensor successfully, but the database entries are missing..
could you add them? if you need more info, tell me how I can help..
this is what the log tells me..

thanks.

[13.12.2020, 01:20:46] [ZigBee] Found ZigBee device:  Device {
  ID: 2,
  _type: 'EndDevice',
  _ieeeAddr: '0x00158d0004522754',
  _networkAddress: 9602,
  _manufacturerID: 4151,
  _endpoints: [
    Endpoint {
      ID: 1,
      profileID: 260,
      deviceID: 1026,
      inputClusters: [Array],
      outputClusters: [Array],
      deviceNetworkAddress: 9602,
      deviceIeeeAddress: '0x00158d0004522754',
      clusters: [Object],
      _binds: [],
      meta: {}
    }
  ],
  _manufacturerName: 'LUMI',
  _powerSource: 'Battery',
  _modelID: 'lumi.sensor_wleak.aq1',
  _applicationVersion: 4,
  _stackVersion: 2,
  _zclVersion: 1,
  _hardwareVersion: 2,
  _dateCode: '20170721',
  _softwareBuildID: '3000-0001',
  _interviewCompleted: true,
  _interviewing: false,
  meta: {},
  _lastSeen: 1607818686439
}
[13.12.2020, 01:20:46] [ZigBee] Unrecognized device: 0x00158d0004522754 LUMI lumi.sensor_wleak.aq1
[13.12.2020, 01:20:46] [ZigBee] Successfully started ZigBee service

**Comment by madchicken** [comment]
v1.0.8 added support for this device, please check it
