### ISSUE TITLE
Plugin Does not recognise Ikea On/Off Switch

### ISSUE THREAD

**Issue by wamfox** [madchicken/homebridge-zigbee-nt#57]
Just updated the plugin to version 1.0.8 and attempted to pair an [Ikea On/Off](https://www.zigbee2mqtt.io/devices/E1743.html) switch. After pairing any time activate the switch I get a "No device found from message". The switch does not show up in homekit.

**Comment by madchicken** [comment]
Please, try to repair the device. It's working fine here in my house (just did the full process).
If the device is paired it should show up in the web interface exposed on port 9000 (same host of homebridge)
