### ISSUE TITLE
"No response" message

### ISSUE THREAD

**Issue by manuchis** [madchicken/homebridge-zigbee-nt#6]
Hi, after some days testing the configuration I notice that some sensors have some delay on updating or do not respond on the Home app. When I push the button it takes a while but then reacts (it is not that it does not have signal, but has some delay). I'm not sure if it is related to the implementation, to the dongle or the raspberry (it only happens with the devices connected with this plugin), but I wonder if you have the same behavior or noticed something similar. 

Thanks again!

**Comment by madchicken** [comment]
Yes, I was observing the same behavior and I think is related to the way I am handling the response. Could you try the RC2 branch and see if it is better? I am out for vacation this week, so it’s difficult for me to try anything

**Comment by manuchis** [comment]
I did the update manually, I think now is better. 
I will keep an eye on it.
