### ISSUE TITLE
HomeKit Switch for pairing doesn‘t show up in Home App

### ISSUE THREAD

**Issue by Ma-Str** [madchicken/homebridge-zigbee-nt#64]
Hello madchicken,

I am currently not able to pair any devices as the HomeKit Switch mentioned in Wiki article „Pairing Devices“ is not present. 
I also find the instructions not clear at all and agree with mojijafari from #63.

Version installed via Homebridge UI: 1.0.10

Thanks,
Ma-Str

**Comment by madchicken** [comment]
If you don't see the pairing button in yours home app, then you have a problem with the installation. You should send me your homebridge logs during a fresh restart

**Comment by Ma-Str** [comment]
Yes, I haven‘t read the instructions clearly and wasn‘t aware that I also need the CC253X Adapter vor it to work. Which I do not have.
Sorry

**Comment by mojijafari** [comment]
First of all, I should thank you again for your kind answer,
I don't have the paring button too. How ever, every zigbee device can connect with hub by reseting it, which seems system is working! But I have no control on it.

**Comment by madchicken** [comment]
If you don't see the button it means the plug-in is not properly configured or your dongle is not supported by the herdsman library. Please provide some startup homebrige log, so I can help you identifying the source of the problem
