### ISSUE TITLE
Xiaomi motion sensor (Feature Request)

### ISSUE THREAD

**Issue by wamfox** [madchicken/homebridge-zigbee-nt#67]
Would it be possible to add this device? I believe it is the same as the Aquara motion sensor just with a slightly different name.

[1/3/2021, 11:14:31] [ZigBee] No device found from message {
  type: 'attributeReport',
  device: Device {
    ID: 4,
    _type: 'EndDevice',
    _ieeeAddr: '0x00158d0003f10d23',
    _networkAddress: 5215,
    _manufacturerID: 4151,
    _endpoints: [ [Endpoint] ],
    _manufacturerName: 'LUMI',
    _powerSource: 'Battery',
    _modelID: 'lumi.sensor_motion',
    _applicationVersion: 11,
    _stackVersion: undefined,
    _zclVersion: undefined,
    _hardwareVersion: undefined,
    _dateCode: undefined,
    _softwareBuildID: undefined,
    _interviewCompleted: true,
    _interviewing: false,
    meta: {},
    _lastSeen: 1609636471177,
    _linkquality: 57
  },
  endpoint: Endpoint {
    ID: 1,
    profileID: undefined,
    deviceID: undefined,
    inputClusters: [],
    outputClusters: [],
    deviceNetworkAddress: 5215,
    deviceIeeeAddress: '0x00158d0003f10d23',
    clusters: { genBasic: [Object], msOccupancySensing: [Object] },
    _binds: [],
    _configuredReportings: [],
    meta: {}
  },
  data: { occupancy: 1 },
  linkquality: 57,
  groupID: 0,
  cluster: 'msOccupancySensing',
  meta: {
    zclTransactionSequenceNumber: 15,
    manufacturerCode: null,
    frameControl: {
      frameType: 0,
      manufacturerSpecific: false,
      direction: 1,
      disableDefaultResponse: true,
      reservedBits: 0
    }
  }
}

**Comment by madchicken** [comment]
Could you please send me the exact model? You can find it in the Zigbee2MQTT devices page https://www.zigbee2mqtt.io/information/supported_devices.html

**Comment by wamfox** [comment]
Sorry should have thought to include this. It is the [RTCGQ01LM](https://www.zigbee2mqtt.io/devices/RTCGQ01LM.html)

**Comment by tr1ng0** [comment]
@madchicken if you didn't already started with this I can have a look. It seems to me we only have to add the modelID and zigbeeID to the index.ts
You can assign me to that if you want

**Comment by madchicken** [comment]
Should be already supported in the unstable branch

**Comment by madchicken** [comment]
Fixed in v2.0.0
