### ISSUE TITLE
Device request

### ISSUE THREAD

**Issue by galzil** [madchicken/homebridge-zigbee-nt#7]
Can you please add Tuya devices?
Specifically [this one](https://www.zigbee2mqtt.io/devices/GDKES-02TZXD.html)
I didn't understand how to add it myself

**Comment by madchicken** [comment]
Shouldn’t be difficult. I’ll try to add it in the RC2

**Comment by galzil** [comment]
Thank you

**Comment by madchicken** [comment]
@galzil Could you try the RC2 branch? I'd like to see if it works before merging into master

**Comment by galzil** [comment]
Thanks, I'll try to install it (HOOBS only installs from NPM)

**Comment by galzil** [comment]
Unfortunatelly, HOOBS doesn't like rc installs, The install failed midway and now the pluging is not loading at all.
I'll re install the master

**Comment by madchicken** [comment]
Ok, let's merge it then and give it a try...

**Comment by madchicken** [comment]
@galzil could you send me the content of your zigbee.db file? Should be in the same folder where you store the homebridge config file

**Comment by madchicken** [comment]
Sorry, I just realised that you cannot run the plugin, so you don't have any db file. I'll release the RC2, let's see how it goes.

**Comment by galzil** [comment]
I'll have to wait a bit, HOOBS still shows only RC1, they have a bit of a delay
