### ISSUE TITLE
Aqara Door Sensor is wrongly open

### ISSUE THREAD

**Issue by tr1ng0** [madchicken/homebridge-zigbee-nt#74]
Hey,
So my Aqara Door Sensor (lumi.sensor_magnet.aq2) started misbehaving on unstable 1&2 (2.0.0). It randomly changes it state to open (therefore triggering linked events to that trigger) even tho the sensor is closed). I tested a little bit and I don't know why but it def. happens every time when reloading Homebridge UI on a browser (it then appears in the home app too) AND when opening home App on iPhone. I believe it has to do with the fact that both UIs (Home App and Browser) when requesting current states of the connected devices (which leads to somehow the sonsor to be set to open even tho the sonsor not reporting it?!). It happened before 2.0.0unstable.2 before but after updating to unstable it starting to go off every time opening a UI which asks for current states. Before 2.0.0 it happened like 1-2 a week max. 

Are any additional informations required?

Thank you :)

**Comment by madchicken** [comment]
@tr1ng0 can you provide some log from homebridge when the sensor triggers? The status of the contact should be sent from the device (is a sort of `push` information) and it is updated automatically in the ZigBeeAccessory class (update method). Since I did a refactoring there, it could be there is a problem reading the new state coming from the device

**Comment by tr1ng0** [comment]
[1/12/2021, 10:40:54 AM] [ZigBee] Zigbee message from 0x00158d00047c66f0 attributeReport
[1/12/2021, 10:40:54 AM] [ZigBee] Decoded state from incoming message { contact: false }
[1/12/2021, 10:40:54 AM] [ZigBee] Updating state of device Aqara door & window contact sensor with  { contact: false }
[1/12/2021, 10:40:54 AM] [ZigBee] Updated state for device Aqara door & window contact sensor is now  { state: 'OFF', contact: false }
[1/12/2021, 10:40:54 AM] [ZigBee] Updating service  (UUID: 00000080-0000-1000-8000-0026BB765291)
[1/12/2021, 10:40:54 AM] [ZigBee] Updating service  (UUID: 00000096-0000-1000-8000-0026BB765291)
[1/12/2021, 10:40:56 AM] [ZigBee] Zigbee message from 0x00158d00047c66f0 attributeReport
[1/12/2021, 10:40:56 AM] [ZigBee] Decoded state from incoming message { contact: true }
[1/12/2021, 10:40:56 AM] [ZigBee] Updating state of device Aqara door & window contact sensor with  { contact: true }
[1/12/2021, 10:40:56 AM] [ZigBee] Updated state for device Aqara door & window contact sensor is now  { state: 'OFF', contact: true }
[1/12/2021, 10:40:56 AM] [ZigBee] Updating service  (UUID: 00000080-0000-1000-8000-0026BB765291)
[1/12/2021, 10:40:56 AM] [ZigBee] Updating service  (UUID: 00000096-0000-1000-8000-0026BB765291)

**Comment by madchicken** [comment]
Seems correct...can you correlate some wrong update with a log? The only thing I can't understand is the `state: OFF`...why is it OFF?

**Comment by tr1ng0** [comment]
I was wondering that too, I'm not sure but could the state OFF be linked to the Battery level saying 0? 

I checked the logs to the behaviour of the Sensor. I can now def say when opening ANY UI (Homebridge Web or Home App) the device triggers (without logging it) the contact: false. I linked homekit automations with a hue lightstrip to see when the state is changing and it changes RIGHT at the moment when opening an UI but does not log it

**Comment by madchicken** [comment]
When you open an HomeKit app, the app is requesting the status of all devices. In this case a call to [this method](https://github.com/madchicken/homebridge-zigbee-nt/blob/master/src/accessories/xiaomi/contact-sensor.ts#L24) should happen. The reported state is the last saved, so it should also be the last reported in logs

**Comment by tr1ng0** [comment]
Weird ... atm the sensor is def. not working like he should. He def. changes the state when requesting the method when opening an UI

**Comment by HalloTschuess** [comment]
@madchicken While playing around with the temperature and humidity builder I noticed that the state is in fact not the last reported state. It it actually stays the same like it when was first initialized. In my case this is `{ state: 'OFF' }`. 

Unfortunately I don't own the door sensor and cannot confirm if this is the problem here but in my case the humidity resets to 0 everytime I open the Home app. Stangely the temperature does get reported correctly even though the state in the temperatuere builder doesn't change as well.

I'm not a NodeJS / Javascript developer (and in general not that experienced) but from some research I found out there might be something going on because there is not pass by reference like in other languages.

When reassigning on object to a variable, the references to it's properties gets lost. I think this happens [while updating the state](https://github.com/madchicken/homebridge-zigbee-nt/blob/a8461e8395332918147344d00628614ac3f1030b/src/accessories/zig-bee-accessory.ts#L191). 

When I pass `ZigBeeAccessory` to `ServiceBuilder` and then directly read the state (eg. `this.zigBeeAccessory.state`) it gets reflected correctly. 

Please correct me if I'm missing something here or if this is even related.

**Comment by maccoylton** [comment]
>@madchicken While playing around with the temperature and humidity builder I noticed that the state is in fact not the last reported state. It it actually stays the same like it when was first initialized. In my case this is `{ state: 'OFF' }`.  ...
I’m seeing an similar issue with my Sonoff door sensor where, it’ll will show open when it actually close

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by madchicken** [comment]
@HalloTschuess I don't think the line you pointed out is causing this issue, although is clear that _there is_ an issue. At that point I simply create a new object with all values from the current state and the incoming one. If the `state` property is not present in the new state, the resulting object will still have the old value (`OFF`).
One question: after updating, the state, I print out the new state (in debug). Do you see the correct values there?

**Comment by HalloTschuess** [comment]
@madchicken 

> One question: after updating, the state, I print out the new state (in debug). Do you see the correct values there?

Yes: 
```
[23/01/2021, 16:49:35] [ZigBee] Updating state of device Aqara temperature, humidity and pressure sensor with  { pressure: 936 }
[23/01/2021, 16:49:35] [ZigBee] Updated state for device Aqara temperature, humidity and pressure sensor is now  { state: 'OFF', temperature: 25.63, humidity: 38.2, pressure: 936 }

**Comment by madchicken** [comment]
Ok, so the state is not reported during update, that's why it stays set to `OFF`...

**Comment by HalloTschuess** [comment]
I still think it has somthing to do with the reference thing i mentioned

I wrote a small program recreation the issue:
```javascript
class Builder {
    state;
    accessory;

    constructor(state, accessory) {
        this.state = state;

        setInterval(() => {
            console.log('Builder state:', this.state);
            console.log('Accessory state:', accessory.state)
        }, 1000);
    }
}

class Accessory {
    state;
    counter;

    constructor() {
        this.state = {state: 'OFF'};
        this.counter = 0;
    }

    start() {
        new Builder(this.state, this);

        setInterval(() => {
            this.counter++;
            this.update({counter: this.counter});
        }, 1000);
    }

    update(newState) {
        this.state = {...this.state, ...newState};

        console.log('Updated state:', this.state);
    }
}

(new Accessory()).start();
```

The output looks like this:
```
Builder state: { state: 'OFF' }
Accessory state: { state: 'OFF' }
Updated state: { state: 'OFF', counter: 1 }
Builder state: { state: 'OFF' }
Accessory state: { state: 'OFF', counter: 1 }
Updated state: { state: 'OFF', counter: 2 }
Builder state: { state: 'OFF' }
Accessory state: { state: 'OFF', counter: 2 }
Updated state: { state: 'OFF', counter: 3 }
Builder state: { state: 'OFF' }
Accessory state: { state: 'OFF', counter: 3 }
Updated state: { state: 'OFF', counter: 4 }

**Comment by madchicken** [comment]
Oh! Now I see the problem: I am passing the state to the builder, but I should actually pass the accessory OR not recreate the state but update its properties

**Comment by madchicken** [comment]
Quick fix: in internalUpdate, just do this:

    this.state = Object.assign(this.state, { ...state } );

instead of using the spread operator and recreate the state object (that is actually changing the reference that the builder still has)

**Comment by madchicken** [comment]
Ok, it's fixed on master. Funny enough, I introduced this bug with one of my last commits on the 2.0.0 (I was using `assign` before)

**Comment by HalloTschuess** [comment]
You are welcome, glad I could help.

**Comment by tr1ng0** [comment]
@HalloTschuess thanks a lot mate!
