### ISSUE TITLE
Error: PanID must be between 0x0000 (0) and 0xFFFF (65535), got 65535.

### ISSUE THREAD

**Issue by HalloTschuess** [madchicken/homebridge-zigbee-nt#78]
Hi,

in zigbee-herdsman 0.13.55 panID gets validated and 0xFFFF is no longer allowed: https://github.com/Koenkk/zigbee-herdsman/commit/47e2f7660e813b02d1cd4441ab0016ce7721d708. 
Therefore the default configuration throws this error: 

![grafik](https://user-images.githubusercontent.com/20882045/104816953-96f78880-581e-11eb-9263-b56c900a2dc0.png)

Additionally setting a custom panId in the config doesn't seem to work for me either because I get the same error.

Edit:
I found a typo: #79. As it is right now, panID will always be set to 0xFFFF which as described doesn't work anymore.

**Comment by madchicken** [comment]
Thanks, I have merged your PR. I'll fix the default config with version 2.0.0 that is "on the way"

**Comment by madchicken** [comment]
Fixed in v2.0.0
