### ISSUE TITLE
for Hoobs users

### ISSUE THREAD

**Issue by galzil** [madchicken/homebridge-zigbee-nt#8]
There seem to be an issue with Hoobs and other pre V.1 users.
`The requested platform "ZigbeeHomebridgeNTPlatform" was not registered by any plugin.
Your config.json is requesting the platform "ZigbeeHomebridgeNTPlatform" which has not been published by any installed plugins.`

I read [here](https://github.com/hjdhjd/homebridge-myq2/issues/63), that this might fix the issue.
changing:
api.registerPlatform(PLATFORM_NAME, ScreenLogicPlatform)
to
api.registerPlatform("homebridge-zigbee-nt", PLATFORM_NAME, ScreenLogicPlatform)

**Comment by madchicken** [comment]
I will push this into RC2

**Comment by galzil** [comment]
Thank you! can't wait to use this plugin

**Comment by galzil** [comment]
Unfortunatell, I'll have to wait for the next release, HOOBS doesn't allow NPM updates

**Comment by madchicken** [comment]
What do you mean, you can uninstall the plugin and install the latest version for sure.

**Comment by galzil** [comment]
I've just updated to rc3, unfortunatelly, I was wrong about the solution, I get the same error.
Is there a special path for the installation? Hoobs has the homebridge in a different location

**Comment by EdwardChamberlain** [comment]
I also receive this error through HOOBS.

**Comment by madchicken** [comment]
I'll take a look to HOOBS API...

**Comment by madchicken** [comment]
Just tested on latest Hoobs version and the plugin works fine. Closing
