### ISSUE TITLE
Please add Mi Smart Natural Gas Detector

### ISSUE THREAD

**Issue by Hi-hass** [madchicken/homebridge-zigbee-nt#81]
Please add Mi Smart Natural Gas Detector
What do I need to offer？

**Comment by madchicken** [comment]
I will add it in the next release. I don't ask anything, but if you want to donate you are more than welcome. You can find my Paypal link in the readme

**Comment by madchicken** [comment]
@Hi-hass I can't find this sensor in the supported devices list here https://www.zigbee2mqtt.io/information/supported_devices.html
Could you point me to the exact model?

**Comment by madchicken** [comment]
I think I found it https://www.zigbee2mqtt.io/devices/JTQJ-BF-01LM_BW.html

**Comment by madchicken** [comment]
Solved in v2.0.0
