### ISSUE TITLE
Problem with Aqara Opple switch 3 bands

### ISSUE THREAD

**Issue by daxterone** [madchicken/homebridge-zigbee-nt#86]
Hi, I have a problem with my aqara opple switch 3 bands with (6 buttons). I see only 4 buttons and remainig 2 buttons is missing.

Can you help me please?

Here is auto config:
`
"root":[5 items
0:{11 items
"ID":int1
"profileID":int260
"deviceID":int261
"inputClusters":[3 items
0:int0
1:int3
2:int1
]
"outputClusters":[4 items
0:int3
1:int6
2:int8
3:int768
]
"deviceNetworkAddress":int24023
"deviceIeeeAddress":string"0x04cf8cdf3c7dd91f"
"clusters":{4 items
"genBasic":{1 item
"attributes":{9 items
"modelId":string"lumi.remote.b686opcn01"
"manufacturerName":string"LUMI"
"powerSource":int3
"zclVersion":int3
"appVersion":int17
"stackVersion":int2
"hwVersion":int1
"dateCode":string"20190730"
"swBuildId":string"2019www."
}
}
"genPowerCfg":{1 item
"attributes":{1 item
"batteryVoltage":int31
}
}
"genMultistateInput":{1 item
"attributes":{1 item
"presentValue":int1
}
}
"aqaraOpple":{1 item
"attributes":{1 item
"247":{2 items
"type":string"Buffer"
"data":[36 items
0:int1
1:int33
2:int40
3:int12
4:int3
5:int40
6:int25
7:int4
8:int33
9:int168
10:int1
11:int5
12:int33
13:int53
14:int0
15:int6
16:int36
17:int2
18:int0
19:int0
20:int0
21:int0
22:int8
23:int33
24:int17
25:int1
26:int10
27:int33
28:int0
29:int0
30:int12
31:int32
32:int1
33:int100
34:int16
35:int0
]
}
}
}
}
"_binds":[4 items
0:{4 items
"cluster":int6
"type":string"endpoint"
"deviceIeeeAddress":string"0x00124b0018e294c2"
"endpointID":int1
}
1:{4 items
"cluster":int8
"type":string"endpoint"
"deviceIeeeAddress":string"0x00124b0018e294c2"
"endpointID":int1
}
2:{4 items
"cluster":int768
"type":string"endpoint"
"deviceIeeeAddress":string"0x00124b0018e294c2"
"endpointID":int1
}
3:{4 items
"cluster":int1
"type":string"endpoint"
"deviceIeeeAddress":string"0x00124b0018e294c2"
"endpointID":int1
}
]
"_configuredReportings":[]0 items
"meta":{}0 items
}
1:{9 items
"ID":int2
"inputClusters":[]0 items
"outputClusters":[]0 items
"deviceNetworkAddress":int24023
"deviceIeeeAddress":string"0x04cf8cdf3c7dd91f"
"clusters":{1 item
"genMultistateInput":{1 item
"attributes":{1 item
"presentValue":int1
}
}
}
"_binds":[]0 items
"_configuredReportings":[]0 items
"meta":{}0 items
}
2:{9 items
"ID":int3
"inputClusters":[]0 items
"outputClusters":[]0 items
"deviceNetworkAddress":int24023
"deviceIeeeAddress":string"0x04cf8cdf3c7dd91f"
"clusters":{1 item
"genMultistateInput":{1 item
"attributes":{1 item
"presentValue":int1
}
}
}
"_binds":[]0 items
"_configuredReportings":[]0 items
"meta":{}0 items
}
3:{9 items
"ID":int4
"inputClusters":[]0 items
"outputClusters":[]0 items
"deviceNetworkAddress":int24023
"deviceIeeeAddress":string"0x04cf8cdf3c7dd91f"
"clusters":{1 item
"genMultistateInput":{1 item
"attributes":{1 item
"presentValue":int1
}
}
}
"_binds":[]0 items
"_configuredReportings":[]0 items
"meta":{}0 items
}
4:{9 items
"ID":int5
"inputClusters":[]0 items
"outputClusters":[]0 items
"deviceNetworkAddress":int24023
"deviceIeeeAddress":string"0x04cf8cdf3c7dd91f"
"clusters":{1 item
"genMultistateInput":{1 item
"attributes":{1 item
"presentValue":int1
}
}
}
"_binds":[]0 items
"_configuredReportings":[]0 items
"meta":{}0 items
}
]
`

**Comment by tr1ng0** [comment]
Yes we are aware of that, I buried in work at the moment but will try to fix this issue by the end of the week!

**Comment by daxterone** [comment]
Thanks. I have found next issue in terminal. I see this there:

(node:8770) UnhandledPromiseRejectionWarning: Error: Write 0x04cf8cdf3c7dd91f/1 aqaraOpple({"mode":1}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":4447,"transactionSequenceNumber":null}) failed (Data request failed with error: 'MAC transaction expired' (240))
    at ZStackAdapter.<anonymous> (/usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:367:23)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:24:58)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:8770) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:8770) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.


BTW do you have donate?

**Comment by tr1ng0** [comment]
@daxterone I just added the missing 2 buttons to support the 6 button version (not merged yet!)

As soon as this is merged let me know if this works (cannot test myself due to not owning the device) 
If this log appears even after unpairing and pairing again (after the update) pls let me/us know!

**Comment by tr1ng0** [comment]
@madchicken @HalloTschuess 
Quick Question guys: The Fix you guys did on the state reporting could this be ralated to my aqara opple switch reporting wrong states as well? Because as soon as I pair the switch with homebridge and assign f.e. the leave scene (which switches ofc. all the lights off and the smart speakers off) randomly triggers then? I tried troubleshooting that for the last couple of days/weeks. The logs don't show any button being pressed. 
When the light is off the light turn randomly on and the other way around, but only when the last change (f.e. lights on) was NOT made by the aqara switch (i have a hue switch and ofc. siri and only by useing them it happens). This random behaviour stops as soon as I unpair the aqara switch so it must be related. Also i tried to not assign any actions to the buttons, then ofc. this behaviour is also not appearing.
Any thoughts?

**Comment by tr1ng0** [comment]
UPDATE: so apperently there is a log about a button beeing pressed (I sat at my desk so the button is not reachable for me and I witnessed the lights and musik going off)

[1/24/2021, 3:58:57 PM] [ZigBee] Zigbee message from 0x04cf8cdf3c7940b9 attributeReport
[1/24/2021, 3:58:57 PM] [ZigBee] Decoded state from incoming message { battery: 100, voltage: 3084 }
[1/24/2021, 3:58:57 PM] [ZigBee] Updating state of device Aqara Opple switch 2 bands with  { battery: 100, voltage: 3084 }
[1/24/2021, 3:58:57 PM] [ZigBee] Updated state for device Aqara Opple switch 2 bands is now  {
  state: 'OFF',
  action: 'button_4_single',
  battery: 100,
  voltage: 3084
}
[1/24/2021, 3:58:57 PM] [ZigBee] Updating service bottom left (UUID: 00000089-0000-1000-8000-0026BB765291)
[1/24/2021, 3:58:57 PM] [ZigBee] Updating service bottom right (UUID: 00000089-0000-1000-8000-0026BB765291)
[1/24/2021, 3:58:57 PM] [ZigBee] Updating service top left (UUID: 00000089-0000-1000-8000-0026BB765291)
[1/24/2021, 3:58:57 PM] [ZigBee] Updating service top right (UUID: 00000089-0000-1000-8000-0026BB765291)
[1/24/2021, 3:58:57 PM] [ZigBee] Updating service  (UUID: 00000096-0000-1000-8000-0026BB765291)

So there must be a state update bug where homebridge thinks the button was pressed (probabably the last button that was pressed)

**Comment by HalloTschuess** [comment]
@tr1ng0 I think when your switch sends an battery update, the the accessory state still holds the state of a previous update. 

`internalUpdate()` of `ZigBeeAccessory` calls [`update()`](https://github.com/madchicken/homebridge-zigbee-nt/blob/5dceaa2fea5ef2c2db35d51d1c9bd4ff629d7313/src/accessories/xiaomi/aqara-opple-switch.ts#L62) every time it receives the new battery level and thus repeating the last action.
To fix this `state.action` should be removed or reset to a neutral action at the end of `update()`.

**Comment by daxterone** [comment]
> @madchicken @HalloTschuess
> Quick Question guys: The Fix you guys did on the state reporting could this be ralated to my aqara opple switch reporting wrong states as well? Because as soon as I pair the switch with homebridge and assign f.e. the leave scene (which switches ofc. all the lights off and the smart speakers off) randomly triggers then? I tried troubleshooting that for the last couple of days/weeks. The logs don't show any button being pressed.
> When the light is off the light turn randomly on and the other way around, but only when the last change (f.e. lights on) was NOT made by the aqara switch (i have a hue switch and ofc. siri and only by useing them it happens). This random behaviour stops as soon as I unpair the aqara switch so it must be related. Also i tried to not assign any actions to the buttons, then ofc. this behaviour is also not appearing.
> Any thoughts?

yes, I have the same problem without any record in log light turn on. This did not happen before installing this plugin.

I see the aqara opple 6b in Paired devices but I do not see in devices. Here is log:

[24. 1. 2021 19:07:54] [ZigBee] No device found from message {
  type: 'commandOff',
  device: Device {
    ID: 3,
    _type: 'EndDevice',
    _ieeeAddr: '0x04cf8cdf3c7dd91f',
    _networkAddress: 45723,
    _manufacturerID: 4447,
    _endpoints: [
      [Endpoint],
      [Endpoint],
      [Endpoint],
      [Endpoint],
      [Endpoint],
      [Endpoint]
    ],
    _manufacturerName: undefined,
    _powerSource: 'Battery',
    _modelID: 'lumi.remote.b686opcn01',
    _applicationVersion: 17,
    _stackVersion: undefined,
    _zclVersion: 3,
    _hardwareVersion: undefined,
    _dateCode: undefined,
    _softwareBuildID: undefined,
    _interviewCompleted: false,
    _interviewing: false,
    meta: {},
    _lastSeen: 1611511674498,
    _linkquality: 118
  },
  endpoint: Endpoint {
    ID: 1,
    profileID: 260,
    deviceID: 261,
    inputClusters: [ 0, 3, 1 ],
    outputClusters: [ 3, 6, 8, 768 ],
    deviceNetworkAddress: 45723,
    deviceIeeeAddress: '0x04cf8cdf3c7dd91f',
    clusters: { genBasic: [Object] },
    _binds: [],
    _configuredReportings: [],
    meta: {}
  },
  data: {},
  linkquality: 118,
  groupID: 0,
  cluster: 'genOnOff',
  meta: {
    zclTransactionSequenceNumber: 5,
    manufacturerCode: null,
    frameControl: {
      frameType: 1,
      manufacturerSpecific: false,
      direction: 0,
      disableDefaultResponse: true,
      reservedBits: 0
    }
  }
}

**Comment by tr1ng0** [comment]
@daxterone pls wait a little longer! We are working on a fix at the moment. Madchicken is preparing an unstable version right now for us to install. I'll let you know when its done (hopefully today)

**Comment by daxterone** [comment]
understood I will help

**Comment by tr1ng0** [comment]
@daxterone it is fixed now! 
Use this command in your homebridge ui Terminal: 
sudo npm i homebridge-zigbee-nt@unstable -g --unsafe-perm
