### ISSUE TITLE
Double device names aqara sensor

### ISSUE THREAD

**Issue by zeno-at** [madchicken/homebridge-zigbee-nt#92]
You build the device names with the serial number of the sensor (temperature), unfortunately you miss the last two characters of the serial number and therefore I got two exact same device names in my case!

**Comment by madchicken** [comment]
AH! I didn't. It is probably a limitation in the name length :(

**Comment by zeno-at** [comment]
Can you shorten the front part of device name to have the full range of the serial number?

**Comment by madchicken** [comment]
Yes, I will ensure that the name won't exceed the maximum length. I still need to find the maximum allowed length tho 😂

**Comment by zeno-at** [comment]
Perfect, thx
