### ISSUE TITLE
Adding LIDL devices

### ISSUE THREAD

**Issue by andreinanu** [madchicken/homebridge-zigbee-nt#99]
Hello,

Since I've seen that LIDL devices are supported [here](https://www.zigbee2mqtt.io/information/supported_devices.html), I've tried following the guide to add the LIDL Motion Sensor HG06337 (seen by HB as TY0202).
The pairing went ok by adding the following info in the config file:

>             "devices": [
                {
                    "manufacturer": "Lidl",
                    "models": [
                        "TY0202"
                    ],
                    "services": [
                        {
                            "type": "motion-sensor",
                            "meta": {
                                "tamper": "true",
                                "batteryLow": "true"
                            }
                        }
                    ]
                } 
The device even shows as connected in the ZigBee NT Web UI, but the problem is that there is no device created in Homebridge, and the output is the following (most likely when detecting motion):

> [26/01/2021, 11:00:09] [ZigBee] No device found from message {
  type: 'commandStatusChangeNotification',
  device: Device {
    ID: 3,
    _type: 'EndDevice',
    _ieeeAddr: '0xec1bbdfffeb8c91d',
    _networkAddress: 51236,
    _manufacturerID: 4619,
    _endpoints: [ [Endpoint] ],
    _manufacturerName: '_TZ1800_fcdjzz3s',
    _powerSource: 'Battery',
    _modelID: 'TY0202',
    _applicationVersion: 65,
    _stackVersion: 2,
    _zclVersion: 1,
    _hardwareVersion: 1,
    _dateCode: '2019.12.12',
    _softwareBuildID: undefined,
    _interviewCompleted: true,
    _interviewing: false,
    meta: {},
    _lastSeen: 1611655209035,
    _linkquality: 78
  },
  endpoint: Endpoint {
    ID: 1,
    profileID: 260,
    deviceID: 1026,
    inputClusters: [ 0, 1, 3, 1280, 2821 ],
    outputClusters: [ 25 ],
    deviceNetworkAddress: 51236,
    deviceIeeeAddress: '0xec1bbdfffeb8c91d',
    clusters: { genBasic: [Object], ssIasZone: [Object], genPowerCfg: [Object] },
    _binds: [],
    _configuredReportings: [],
    meta: {}
  },
  data: { zonestatus: 36, extendedstatus: 0 },
  linkquality: 78,
  groupID: 0,
  cluster: 'ssIasZone',
  meta: {
    zclTransactionSequenceNumber: 38,
    manufacturerCode: null,
    frameControl: {
      frameType: 1,
      manufacturerSpecific: false,
      direction: 1,
      disableDefaultResponse: false,
      reservedBits: 0
    }
  }
}

Since LIDL devices are not directly supported by the plugin, I am merely asking for a bit of guidance, if possible.
LIDL started pretty strong in Europe with these devices, so I assume the adoption will only increase in the upcoming period.

Thank you!
Andrei

**Comment by tr1ng0** [comment]
Hey @andreinanu 
Is it that [device](https://www.zigbee2mqtt.io/devices/HG06335.html)?

**Comment by tr1ng0** [comment]
@andreinanu sorry to hear ... 
maybe @madchicken can help out here?

**Comment by madchicken** [comment]
The model is correct, what is not is the manufacturer: from the device info I see in your first post it should be `_TZ1800_fcdjzz3s`

**Comment by andreinanu** [comment]
@madchicken it was foolish of me to think that the precise name was not mandatory there, you are absolutely right. Added the name and it works flawlessly. 

Many thanks to both of you for the guidance!
I'll go ahead and close the issue and buy some more LIDL devices :)

**Comment by madchicken** [comment]
Thanks @andreinanu I will permanently add this device in the internal database
